# -*- coding: utf-8 -*-
"""01_Task1_BERT_MusicCaps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzFXb7TeaVQxvKzHKgRVjMIhiSwfbIWq
"""

from datasets import load_dataset

dataset = load_dataset(
    "google/MusicCaps",
    split="train"
)

print(dataset)
print(dataset.column_names)

df = dataset.to_pandas()

print(df.shape)
df[["caption", "aspect_list"]].head()

import ast

def parse_aspects(x):
    if isinstance(x, list):
        return x

    if isinstance(x, str):
        try:
            value = ast.literal_eval(x)
            if isinstance(value, list):
                return value
        except:
            pass

    return []

df["tags"] = df["aspect_list"].apply(parse_aspects)

print(df["tags"].iloc[0])
print(type(df["tags"].iloc[0]))

from collections import Counter

tag_counts = Counter()

for tags in df["tags"]:
    tag_counts.update(tags)

print("Number of unique tags:", len(tag_counts))

top_50 = tag_counts.most_common(50)

for i, (tag, count) in enumerate(top_50, start=1):
    print(f"{i:2d}. {tag:40s} {count}")

TOP_K = 50

selected_tags = [tag for tag, count in tag_counts.most_common(TOP_K)]

print("Selected labels:")
for i, tag in enumerate(selected_tags):
    print(i, tag)

import numpy as np

tag_to_id = {
    tag: i
    for i, tag in enumerate(selected_tags)
}

def make_label_vector(tags):
    labels = np.zeros(TOP_K, dtype=np.float32)

    for tag in tags:
        if tag in tag_to_id:
            labels[tag_to_id[tag]] = 1.0

    return labels

df["labels"] = df["tags"].apply(make_label_vector)

print("Caption:")
print(df.iloc[0]["caption"])

print("\nOriginal tags:")
print(df.iloc[0]["tags"])

print("\n50-dimensional target:")
print(df.iloc[0]["labels"])

before = len(df)

df = df[
    df["labels"].apply(lambda x: x.sum() > 0)
].reset_index(drop=True)

after = len(df)

print("Before:", before)
print("After:", after)
print("Removed:", before - after)

df["num_labels"] = df["labels"].apply(lambda x: int(x.sum()))

print(df["num_labels"].describe())

df[["caption", "tags", "num_labels"]].head()

from google.colab import drive
drive.mount('/content/drive')

import os

TASK1_DIR = "/content/drive/MyDrive/CSE425_GNN_BERT_Music/Task1_MusicCaps"

os.makedirs(TASK1_DIR, exist_ok=True)

print(TASK1_DIR)

from sklearn.model_selection import train_test_split

model_df = df[["caption", "labels"]].copy()

# Convert numpy arrays to normal Python lists
model_df["labels"] = model_df["labels"].apply(lambda x: x.tolist())

train_df, temp_df = train_test_split(
    model_df,
    test_size=0.20,
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=42
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))
print("Total:", len(train_df) + len(val_df) + len(test_df))

from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_df.reset_index(drop=True)
)

val_dataset = Dataset.from_pandas(
    val_df.reset_index(drop=True)
)

test_dataset = Dataset.from_pandas(
    test_df.reset_index(drop=True)
)

print(train_dataset)
print(val_dataset)
print(test_dataset)

from transformers import AutoTokenizer

MODEL_NAME = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Tokenizer loaded.")

def tokenize_function(batch):
    return tokenizer(
        batch["caption"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_tokenized = train_dataset.map(
    tokenize_function,
    batched=True
)

val_tokenized = val_dataset.map(
    tokenize_function,
    batched=True
)

test_tokenized = test_dataset.map(
    tokenize_function,
    batched=True
)

print(train_tokenized)

from transformers import AutoModelForSequenceClassification

id2label = {
    i: label
    for i, label in enumerate(selected_tags)
}

label2id = {
    label: i
    for i, label in enumerate(selected_tags)
}

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=TOP_K,
    problem_type="multi_label_classification",
    id2label=id2label,
    label2id=label2id
)

print("Model loaded.")
print("Number of labels:", model.config.num_labels)

import numpy as np

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score
)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    probabilities = sigmoid(logits)

    predictions = (
        probabilities >= 0.5
    ).astype(int)

    labels = labels.astype(int)

    micro_f1 = f1_score(
        labels,
        predictions,
        average="micro",
        zero_division=0
    )

    macro_f1 = f1_score(
        labels,
        predictions,
        average="macro",
        zero_division=0
    )

    micro_precision = precision_score(
        labels,
        predictions,
        average="micro",
        zero_division=0
    )

    micro_recall = recall_score(
        labels,
        predictions,
        average="micro",
        zero_division=0
    )

    return {
        "micro_f1": micro_f1,
        "macro_f1": macro_f1,
        "micro_precision": micro_precision,
        "micro_recall": micro_recall
    }

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir=TASK1_DIR + "/checkpoints",

    learning_rate=2e-5,

    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,

    num_train_epochs=3,

    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",

    logging_steps=50,

    load_best_model_at_end=True,

    metric_for_best_model="micro_f1",
    greater_is_better=True,

    save_total_limit=1,

    fp16=torch.cuda.is_available(),

    report_to="none",

    seed=42
)

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,

    processing_class=tokenizer,

    compute_metrics=compute_metrics
)

print("Trainer ready.")

train_result = trainer.train()

FINAL_MODEL_DIR = TASK1_DIR + "/final_model"

trainer.save_model(FINAL_MODEL_DIR)
tokenizer.save_pretrained(FINAL_MODEL_DIR)

print("Saved to:")
print(FINAL_MODEL_DIR)

# Get predictions on validation set
val_output = trainer.predict(val_tokenized)

val_logits = val_output.predictions
val_labels = val_output.label_ids.astype(int)

val_probs = sigmoid(val_logits)

print("Validation predictions ready.")
print("Shape:", val_probs.shape)

from sklearn.metrics import f1_score
import numpy as np

threshold_results = []

for threshold in np.arange(0.05, 0.55, 0.05):

    predictions = (val_probs >= threshold).astype(int)

    micro = f1_score(
        val_labels,
        predictions,
        average="micro",
        zero_division=0
    )

    macro = f1_score(
        val_labels,
        predictions,
        average="macro",
        zero_division=0
    )

    threshold_results.append(
        (threshold, micro, macro)
    )

    print(
        f"Threshold={threshold:.2f} | "
        f"Micro-F1={micro:.4f} | "
        f"Macro-F1={macro:.4f}"
    )

best_threshold, best_micro, best_macro = max(
    threshold_results,
    key=lambda x: x[1]
)

print("\nBEST THRESHOLD")
print("Threshold:", round(best_threshold, 2))
print("Validation Micro-F1:", round(best_micro, 4))
print("Validation Macro-F1:", round(best_macro, 4))

test_output = trainer.predict(test_tokenized)

test_logits = test_output.predictions
test_labels = test_output.label_ids.astype(int)

test_probs = sigmoid(test_logits)

test_predictions = (
    test_probs >= best_threshold
).astype(int)

from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score
)

test_micro_f1 = f1_score(
    test_labels,
    test_predictions,
    average="micro",
    zero_division=0
)

test_macro_f1 = f1_score(
    test_labels,
    test_predictions,
    average="macro",
    zero_division=0
)

test_precision = precision_score(
    test_labels,
    test_predictions,
    average="micro",
    zero_division=0
)

test_recall = recall_score(
    test_labels,
    test_predictions,
    average="micro",
    zero_division=0
)

print("FINAL TEST RESULTS")
print("------------------")
print("Threshold:", round(best_threshold, 2))
print("Micro-F1:", round(test_micro_f1, 4))
print("Macro-F1:", round(test_macro_f1, 4))
print("Micro Precision:", round(test_precision, 4))
print("Micro Recall:", round(test_recall, 4))

import matplotlib.pyplot as plt

eval_logs = [
    log for log in trainer.state.log_history
    if "eval_micro_f1" in log
]

epochs = [log["epoch"] for log in eval_logs]
micro_f1_values = [log["eval_micro_f1"] for log in eval_logs]
macro_f1_values = [log["eval_macro_f1"] for log in eval_logs]

plt.figure(figsize=(7, 5))

plt.plot(
    epochs,
    micro_f1_values,
    marker="o",
    label="Micro-F1"
)

plt.plot(
    epochs,
    macro_f1_values,
    marker="o",
    label="Macro-F1"
)

plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.title("Task 1: F1 Score vs Training Epoch")
plt.xticks(epochs)
plt.legend()
plt.grid(True, alpha=0.3)

plt.savefig(
    TASK1_DIR + "/f1_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

val_losses = [
    log["eval_loss"]
    for log in eval_logs
]

plt.figure(figsize=(7, 5))

plt.plot(
    epochs,
    val_losses,
    marker="o"
)

plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Task 1: Validation Loss vs Epoch")
plt.xticks(epochs)
plt.grid(True, alpha=0.3)

plt.savefig(
    TASK1_DIR + "/validation_loss.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

for i in range(5):

    caption = test_df.iloc[i]["caption"]

    true_vector = np.array(
        test_df.iloc[i]["labels"]
    )

    pred_vector = test_predictions[i]

    true_tags = [
        selected_tags[j]
        for j in range(TOP_K)
        if true_vector[j] == 1
    ]

    predicted_tags = [
        selected_tags[j]
        for j in range(TOP_K)
        if pred_vector[j] == 1
    ]

    print("=" * 80)
    print(f"EXAMPLE {i + 1}")

    print("\nCaption:")
    print(caption)

    print("\nTrue Top-50 Tags:")
    print(true_tags)

    print("\nPredicted Tags:")
    print(predicted_tags)

    print()

import json

results = {
    "dataset": "google/MusicCaps",
    "model": "distilbert-base-uncased",
    "number_of_labels": TOP_K,
    "training_examples": len(train_df),
    "validation_examples": len(val_df),
    "test_examples": len(test_df),

    "epochs": 3,

    "best_threshold": float(best_threshold),

    "test_micro_f1": float(test_micro_f1),
    "test_macro_f1": float(test_macro_f1),
    "test_micro_precision": float(test_precision),
    "test_micro_recall": float(test_recall)
}

with open(
    TASK1_DIR + "/task1_results.json",
    "w"
) as f:

    json.dump(
        results,
        f,
        indent=4
    )

print(results)