# -*- coding: utf-8 -*-
"""02_Task2_GNN_GTZAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0AmlfKewu3dWsi6GpSEFowGieYHuE_s
"""

import torch

print("PyTorch:", torch.__version__)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

!wget -O /content/genres.tar.gz \
"https://huggingface.co/datasets/marsyas/gtzan/resolve/main/data/genres.tar.gz?download=true"

import os

file_path = "/content/genres.tar.gz"

print("File exists:", os.path.exists(file_path))

if os.path.exists(file_path):
    print(
        "Size:",
        round(os.path.getsize(file_path) / (1024**3), 2),
        "GB"
    )

!mkdir -p /content/gtzan
!tar -xzf /content/genres.tar.gz -C /content/gtzan

!find /content/gtzan -maxdepth 2 -type d | head -20

!find /content/gtzan -type f | head -30

!find /content/gtzan -maxdepth 4 -type d | head -50

import glob
import os

blues_folders = glob.glob(
    "/content/**/blues",
    recursive=True
)

print("Possible blues folders:")

for folder in blues_folders:
    print(folder)

import glob
import os

blues_folders = glob.glob(
    "/content/**/blues",
    recursive=True
)

valid_blues_folders = [
    folder for folder in blues_folders
    if os.path.isdir(folder)
]

print(valid_blues_folders)

if len(valid_blues_folders) > 0:
    GTZAN_DIR = os.path.dirname(valid_blues_folders[0])
    print("\nGTZAN_DIR =", GTZAN_DIR)
else:
    print("Could not find GTZAN genre folders.")

genres = [
    "blues",
    "classical",
    "country",
    "disco",
    "hiphop",
    "jazz",
    "metal",
    "pop",
    "reggae",
    "rock"
]

total_tracks = 0

for genre in genres:

    genre_dir = os.path.join(
        GTZAN_DIR,
        genre
    )

    files = []

    for extension in ["*.au", "*.wav", "*.mp3", "*.flac"]:
        files.extend(
            glob.glob(
                os.path.join(
                    genre_dir,
                    extension
                )
            )
        )

    print(
        f"{genre:10s}: {len(files)} tracks"
    )

    total_tracks += len(files)

print("\nTotal tracks:", total_tracks)

!find /content/gtzan -type f | head -30

import librosa
import glob
import os

# Get normal WAV files only, ignoring ._ metadata files
example_files = [
    p for p in glob.glob(
        os.path.join(GTZAN_DIR, "blues", "*.wav")
    )
    if not os.path.basename(p).startswith("._")
]

example_path = sorted(example_files)[0]

audio, sr = librosa.load(
    example_path,
    sr=22050,
    mono=True
)

genre = os.path.basename(
    os.path.dirname(example_path)
)

print("File:", example_path)
print("Genre:", genre)
print("Sampling rate:", sr)
print("Samples:", len(audio))
print("Duration:", round(len(audio) / sr, 2), "seconds")

from IPython.display import Audio, display

display(
    Audio(
        audio,
        rate=sr
    )
)

import numpy as np

TARGET_SECONDS = 30
target_length = TARGET_SECONDS * sr

if len(audio) < target_length:
    audio = np.pad(
        audio,
        (0, target_length - len(audio))
    )
else:
    audio = audio[:target_length]

print(
    "Final duration:",
    len(audio) / sr,
    "seconds"
)

SEGMENT_SECONDS = 5
segment_length = SEGMENT_SECONDS * sr

segments = []

for i in range(6):

    start = i * segment_length
    end = start + segment_length

    segment = audio[start:end]
    segments.append(segment)

print("Number of segments:", len(segments))

for i, segment in enumerate(segments):
    print(
        f"Node {i + 1}:",
        len(segment) / sr,
        "seconds"
    )

node_features = []

for segment in segments:

    chroma = librosa.feature.chroma_stft(
        y=segment,
        sr=sr,
        n_chroma=12
    )

    # Average over time
    chroma_mean = np.mean(
        chroma,
        axis=1
    )

    node_features.append(chroma_mean)

node_features = np.array(node_features)

print(
    "Node feature matrix shape:",
    node_features.shape
)

print("\nNode 1 features:")
print(node_features[0])

edge_set = set()

num_nodes = len(node_features)

for i in range(num_nodes - 1):

    edge_set.add((i, i + 1))
    edge_set.add((i + 1, i))

print("Temporal directed edges:")
print(sorted(edge_set))

from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(
    node_features
)

print(
    np.round(
        similarity_matrix,
        3
    )
)

SIMILARITY_THRESHOLD = 0.90

similarity_edges = []

for i in range(num_nodes):

    for j in range(i + 1, num_nodes):

        # Consecutive nodes already have temporal edges
        if j == i + 1:
            continue

        if similarity_matrix[i, j] >= SIMILARITY_THRESHOLD:

            edge_set.add((i, j))
            edge_set.add((j, i))

            similarity_edges.append(
                (
                    i,
                    j,
                    similarity_matrix[i, j]
                )
            )

print("Additional similarity edges:")

for i, j, score in similarity_edges:
    print(
        f"Node {i+1} <-> Node {j+1}",
        f"Similarity = {score:.3f}"
    )

print(
    "\nTotal directed edges:",
    len(edge_set)
)

edges = sorted(list(edge_set))

edge_index = np.array(
    edges,
    dtype=np.int64
).T

print(
    "edge_index shape:",
    edge_index.shape
)

print(edge_index)

import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

# Nodes
for i in range(num_nodes):
    G.add_node(i)

# Temporal edges
for i in range(num_nodes - 1):
    G.add_edge(i, i + 1)

# Similarity edges
for i, j, score in similarity_edges:
    G.add_edge(i, j)

pos = {
    i: (i, 0)
    for i in range(num_nodes)
}

labels = {
    i: f"Segment {i + 1}"
    for i in range(num_nodes)
}

plt.figure(figsize=(10, 4))

nx.draw(
    G,
    pos,
    labels=labels,
    with_labels=True,
    node_size=2500,
    font_size=9
)

plt.title(
    f"GTZAN Segment Graph - {genre}"
)

plt.show()

import torch

from torch_geometric.data import Data

genre_to_id = {
    genre_name: i
    for i, genre_name in enumerate(genres)
}

graph = Data(
    x=torch.tensor(
        node_features,
        dtype=torch.float
    ),

    edge_index=torch.tensor(
        edge_index,
        dtype=torch.long
    ),

    y=torch.tensor(
        [genre_to_id[genre]],
        dtype=torch.long
    )
)

print(graph)

print(
    "\nNode feature shape:",
    graph.x.shape
)

print(
    "Edge shape:",
    graph.edge_index.shape
)

print(
    "Genre ID:",
    graph.y.item()
)

print(
    "Genre:",
    genre
)

SIMILARITY_THRESHOLD = 0.99

edge_set = set()

num_nodes = len(node_features)

# 1. Temporal edges
for i in range(num_nodes - 1):
    edge_set.add((i, i + 1))
    edge_set.add((i + 1, i))

# 2. Similarity edges
similarity_edges = []

for i in range(num_nodes):
    for j in range(i + 1, num_nodes):

        # Already connected temporally
        if j == i + 1:
            continue

        if similarity_matrix[i, j] >= SIMILARITY_THRESHOLD:

            edge_set.add((i, j))
            edge_set.add((j, i))

            similarity_edges.append(
                (i, j, similarity_matrix[i, j])
            )

edges = sorted(list(edge_set))

edge_index = np.array(
    edges,
    dtype=np.int64
).T

print("Similarity threshold:", SIMILARITY_THRESHOLD)

print("\nExtra similarity edges:")
for i, j, score in similarity_edges:
    print(
        f"Segment {i+1} <-> Segment {j+1}: "
        f"{score:.4f}"
    )

print("\nTotal directed edges:", len(edge_set))
print("edge_index shape:", edge_index.shape)

graph = Data(
    x=torch.tensor(
        node_features,
        dtype=torch.float
    ),

    edge_index=torch.tensor(
        edge_index,
        dtype=torch.long
    ),

    y=torch.tensor(
        [genre_to_id[genre]],
        dtype=torch.long
    )
)

print(graph)

from sklearn.metrics.pairwise import cosine_similarity
from torch_geometric.data import Data
import numpy as np
import librosa
import torch
import os


SR = 22050
TARGET_SECONDS = 30
SEGMENT_SECONDS = 5
NUM_SEGMENTS = 6
SIMILARITY_THRESHOLD = 0.99


def build_music_graph(audio_path, genre_name):

    # -------------------------
    # 1. Load audio
    # -------------------------
    audio, sr = librosa.load(
        audio_path,
        sr=SR,
        mono=True
    )

    # -------------------------
    # 2. Make exactly 30 sec
    # -------------------------
    target_length = TARGET_SECONDS * SR

    if len(audio) < target_length:
        audio = np.pad(
            audio,
            (0, target_length - len(audio))
        )
    else:
        audio = audio[:target_length]

    # -------------------------
    # 3. Divide into 6 segments
    # -------------------------
    segment_length = SEGMENT_SECONDS * SR

    node_features = []

    for i in range(NUM_SEGMENTS):

        start = i * segment_length
        end = start + segment_length

        segment = audio[start:end]

        # -------------------------
        # 4. Chroma features
        # -------------------------
        chroma = librosa.feature.chroma_stft(
            y=segment,
            sr=SR,
            n_chroma=12
        )

        chroma_mean = np.mean(
            chroma,
            axis=1
        )

        node_features.append(chroma_mean)

    node_features = np.array(
        node_features,
        dtype=np.float32
    )

    # -------------------------
    # 5. Similarity matrix
    # -------------------------
    similarity_matrix = cosine_similarity(
        node_features
    )

    edge_set = set()

    # -------------------------
    # 6. Temporal edges
    # -------------------------
    for i in range(NUM_SEGMENTS - 1):

        edge_set.add((i, i + 1))
        edge_set.add((i + 1, i))

    # -------------------------
    # 7. Similarity edges
    # -------------------------
    for i in range(NUM_SEGMENTS):

        for j in range(i + 1, NUM_SEGMENTS):

            if j == i + 1:
                continue

            if (
                similarity_matrix[i, j]
                >= SIMILARITY_THRESHOLD
            ):

                edge_set.add((i, j))
                edge_set.add((j, i))

    edge_index = np.array(
        sorted(list(edge_set)),
        dtype=np.int64
    ).T

    # -------------------------
    # 8. PyTorch Geometric graph
    # -------------------------
    graph = Data(

        x=torch.tensor(
            node_features,
            dtype=torch.float
        ),

        edge_index=torch.tensor(
            edge_index,
            dtype=torch.long
        ),

        y=torch.tensor(
            [genre_to_id[genre_name]],
            dtype=torch.long
        )
    )

    return graph

test_graph = build_music_graph(
    example_path,
    "blues"
)

print(test_graph)

print(
    "Nodes:",
    test_graph.num_nodes
)

print(
    "Node features:",
    test_graph.x.shape
)

print(
    "Edges:",
    test_graph.edge_index.shape
)

print(
    "Label:",
    test_graph.y.item()
)

from google.colab import drive

drive.mount("/content/drive")

TASK2_DIR = (
    "/content/drive/MyDrive/"
    "CSE425_GNN_BERT_Music/"
    "Task2_GTZAN"
)

GRAPH_SAMPLE_DIR = (
    TASK2_DIR + "/graph_samples"
)

MODEL_DIR = (
    TASK2_DIR + "/models"
)

RESULT_DIR = (
    TASK2_DIR + "/results"
)

PLOT_DIR = (
    TASK2_DIR + "/plots"
)

for directory in [
    TASK2_DIR,
    GRAPH_SAMPLE_DIR,
    MODEL_DIR,
    RESULT_DIR,
    PLOT_DIR
]:
    os.makedirs(
        directory,
        exist_ok=True
    )

print("Task 2 folders ready.")

audio_items = []

for genre_name in genres:

    genre_dir = os.path.join(
        GTZAN_DIR,
        genre_name
    )

    files = sorted(
        glob.glob(
            os.path.join(
                genre_dir,
                "*.wav"
            )
        )
    )

    files = [
        path
        for path in files
        if not os.path.basename(path).startswith("._")
    ]

    for path in files:

        audio_items.append(
            (path, genre_name)
        )

print(
    "Total audio tracks:",
    len(audio_items)
)

from tqdm.auto import tqdm

graphs = []
failed_files = []

for audio_path, genre_name in tqdm(
    audio_items,
    desc="Building GTZAN graphs"
):

    try:

        graph = build_music_graph(
            audio_path,
            genre_name
        )

        graphs.append(graph)

    except Exception as e:

        failed_files.append(
            (
                audio_path,
                str(e)
            )
        )

print("\nGraph construction finished.")

print(
    "Graphs created:",
    len(graphs)
)

print(
    "Failed files:",
    len(failed_files)
)

print("Number of graphs:", len(graphs))

print("\nFirst graph:")
print(graphs[0])

print("\nLast graph:")
print(graphs[-1])

from collections import Counter

graph_labels = [
    int(graph.y.item())
    for graph in graphs
]

label_counts = Counter(graph_labels)

print("Class distribution:")

for label_id in range(len(genres)):
    print(
        f"{label_id}: {genres[label_id]:10s} "
        f"{label_counts[label_id]} graphs"
    )

import numpy as np
from sklearn.model_selection import train_test_split

indices = np.arange(len(graphs))
labels = np.array(graph_labels)

train_idx, temp_idx = train_test_split(
    indices,
    test_size=0.20,
    random_state=42,
    stratify=labels
)

val_idx, test_idx = train_test_split(
    temp_idx,
    test_size=0.50,
    random_state=42,
    stratify=labels[temp_idx]
)

train_graphs = [graphs[i] for i in train_idx]
val_graphs = [graphs[i] for i in val_idx]
test_graphs = [graphs[i] for i in test_idx]

print("Train:", len(train_graphs))
print("Validation:", len(val_graphs))
print("Test:", len(test_graphs))
print(
    "Total:",
    len(train_graphs)
    + len(val_graphs)
    + len(test_graphs)
)

def show_distribution(graph_list, name):

    counts = Counter(
        int(g.y.item())
        for g in graph_list
    )

    print(f"\n{name}")

    for i, genre_name in enumerate(genres):
        print(
            f"{genre_name:10s}: {counts[i]}"
        )


show_distribution(train_graphs, "TRAIN")
show_distribution(val_graphs, "VALIDATION")
show_distribution(test_graphs, "TEST")

from torch_geometric.loader import DataLoader

train_loader = DataLoader(
    train_graphs,
    batch_size=32,
    shuffle=True
)

val_loader = DataLoader(
    val_graphs,
    batch_size=32,
    shuffle=False
)

test_loader = DataLoader(
    test_graphs,
    batch_size=32,
    shuffle=False
)

batch = next(iter(train_loader))

print(batch)
print("Node features:", batch.x.shape)
print("Labels:", batch.y.shape)
print("Number of graphs:", batch.num_graphs)

import torch
import torch.nn.functional as F

from torch.nn import Linear
from torch_geometric.nn import (
    SAGEConv,
    global_mean_pool
)


class GraphSAGEClassifier(torch.nn.Module):

    def __init__(
        self,
        input_dim=12,
        hidden_dim=64,
        num_classes=10,
        dropout=0.3
    ):

        super().__init__()

        self.conv1 = SAGEConv(
            input_dim,
            hidden_dim
        )

        self.conv2 = SAGEConv(
            hidden_dim,
            hidden_dim
        )

        self.classifier = Linear(
            hidden_dim,
            num_classes
        )

        self.dropout = dropout


    def forward(
        self,
        x,
        edge_index,
        batch
    ):

        # GraphSAGE layer 1
        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = F.dropout(
            x,
            p=self.dropout,
            training=self.training
        )

        # GraphSAGE layer 2
        x = self.conv2(
            x,
            edge_index
        )

        x = F.relu(x)

        # Convert all nodes of one song
        # into one graph representation
        x = global_mean_pool(
            x,
            batch
        )

        # 10 genre logits
        x = self.classifier(x)

        return x

device = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

model = GraphSAGEClassifier(
    input_dim=12,
    hidden_dim=64,
    num_classes=10,
    dropout=0.3
).to(device)

print(model)
print("\nDevice:", device)

criterion = torch.nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001,
    weight_decay=1e-4
)

def train_one_epoch():

    model.train()

    total_loss = 0

    for batch in train_loader:

        batch = batch.to(device)

        optimizer.zero_grad()

        output = model(
            batch.x,
            batch.edge_index,
            batch.batch
        )

        labels = batch.y.view(-1)

        loss = criterion(
            output,
            labels
        )

        loss.backward()

        optimizer.step()

        total_loss += (
            loss.item()
            * batch.num_graphs
        )

    return (
        total_loss
        / len(train_loader.dataset)
    )

from sklearn.metrics import (
    accuracy_score,
    f1_score
)


@torch.no_grad()
def evaluate(loader):

    model.eval()

    all_true = []
    all_pred = []

    total_loss = 0

    for batch in loader:

        batch = batch.to(device)

        output = model(
            batch.x,
            batch.edge_index,
            batch.batch
        )

        labels = batch.y.view(-1)

        loss = criterion(
            output,
            labels
        )

        total_loss += (
            loss.item()
            * batch.num_graphs
        )

        predictions = (
            output.argmax(dim=1)
        )

        all_true.extend(
            labels.cpu().numpy()
        )

        all_pred.extend(
            predictions.cpu().numpy()
        )

    average_loss = (
        total_loss
        / len(loader.dataset)
    )

    accuracy = accuracy_score(
        all_true,
        all_pred
    )

    macro_f1 = f1_score(
        all_true,
        all_pred,
        average="macro",
        zero_division=0
    )

    micro_f1 = f1_score(
        all_true,
        all_pred,
        average="micro",
        zero_division=0
    )

    return (
        average_loss,
        accuracy,
        macro_f1,
        micro_f1,
        all_true,
        all_pred
    )

import copy

NUM_EPOCHS = 50

history = {
    "train_loss": [],
    "val_loss": [],
    "val_accuracy": [],
    "val_macro_f1": [],
    "val_micro_f1": []
}

best_val_f1 = -1
best_epoch = 0
best_model_state = None


for epoch in range(
    1,
    NUM_EPOCHS + 1
):

    train_loss = train_one_epoch()

    (
        val_loss,
        val_accuracy,
        val_macro_f1,
        val_micro_f1,
        _,
        _
    ) = evaluate(val_loader)

    history["train_loss"].append(
        train_loss
    )

    history["val_loss"].append(
        val_loss
    )

    history["val_accuracy"].append(
        val_accuracy
    )

    history["val_macro_f1"].append(
        val_macro_f1
    )

    history["val_micro_f1"].append(
        val_micro_f1
    )

    if val_macro_f1 > best_val_f1:

        best_val_f1 = val_macro_f1
        best_epoch = epoch

        best_model_state = copy.deepcopy(
            model.state_dict()
        )

    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Acc: {val_accuracy:.4f} | "
            f"Macro-F1: {val_macro_f1:.4f} | "
            f"Micro-F1: {val_micro_f1:.4f}"
        )


print("\nBest epoch:", best_epoch)
print(
    "Best validation Macro-F1:",
    round(best_val_f1, 4)
)

(
    test_loss,
    test_accuracy,
    test_macro_f1,
    test_micro_f1,
    test_true,
    test_pred
) = evaluate(test_loader)


print("FINAL GRAPHSAGE TEST RESULTS")
print("----------------------------")

print(
    "Test Loss:",
    round(test_loss, 4)
)

print(
    "Accuracy:",
    round(test_accuracy, 4)
)

print(
    "Macro-F1:",
    round(test_macro_f1, 4)
)

print(
    "Micro-F1:",
    round(test_micro_f1, 4)
)

import matplotlib.pyplot as plt

epochs = range(
    1,
    len(history["train_loss"]) + 1
)

plt.figure(figsize=(7, 5))

plt.plot(
    epochs,
    history["train_loss"],
    label="Train Loss"
)

plt.plot(
    epochs,
    history["val_loss"],
    label="Validation Loss"
)

plt.axvline(
    best_epoch,
    linestyle="--",
    label=f"Best Epoch ({best_epoch})"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("GraphSAGE Training and Validation Loss")
plt.legend()
plt.grid(True, alpha=0.3)

plt.savefig(
    PLOT_DIR + "/graphsage_loss_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(7, 5))

plt.plot(
    epochs,
    history["val_macro_f1"],
    label="Validation Macro-F1"
)

plt.plot(
    epochs,
    history["val_micro_f1"],
    label="Validation Micro-F1"
)

plt.axvline(
    best_epoch,
    linestyle="--",
    label=f"Best Epoch ({best_epoch})"
)

plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.title("GraphSAGE Validation F1 vs Epoch")
plt.legend()
plt.grid(True, alpha=0.3)

plt.savefig(
    PLOT_DIR + "/graphsage_f1_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

cm = confusion_matrix(
    test_true,
    test_pred
)

plt.figure(figsize=(9, 8))

plt.imshow(cm)

plt.title(
    "GraphSAGE Confusion Matrix - GTZAN"
)

plt.xlabel("Predicted Genre")
plt.ylabel("True Genre")

plt.xticks(
    range(len(genres)),
    genres,
    rotation=45,
    ha="right"
)

plt.yticks(
    range(len(genres)),
    genres
)

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):

        plt.text(
            j,
            i,
            cm[i, j],
            ha="center",
            va="center"
        )

plt.colorbar()
plt.tight_layout()

plt.savefig(
    PLOT_DIR + "/graphsage_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import classification_report

report = classification_report(
    test_true,
    test_pred,
    target_names=genres,
    digits=4,
    zero_division=0
)

print(report)

graphsage_results = {
    "dataset": "GTZAN",
    "model": "GraphSAGE",
    "graphs_created": len(graphs),
    "failed_tracks": len(failed_files),

    "node_features": "12-dimensional mean chroma",
    "segments_per_track": 6,
    "segment_duration_seconds": 5,
    "similarity_threshold": 0.99,

    "train_size": len(train_graphs),
    "validation_size": len(val_graphs),
    "test_size": len(test_graphs),

    "best_epoch": best_epoch,
    "best_validation_macro_f1": float(best_val_f1),

    "test_loss": float(test_loss),
    "test_accuracy": float(test_accuracy),
    "test_macro_f1": float(test_macro_f1),
    "test_micro_f1": float(test_micro_f1),

    "failed_file": (
        failed_files[0][0]
        if len(failed_files) > 0
        else None
    )
}

with open(
    RESULT_DIR + "/graphsage_results.json",
    "w"
) as f:

    json.dump(
        graphsage_results,
        f,
        indent=4
    )

print(
    json.dumps(
        graphsage_results,
        indent=4
    )
)

print("Graphs:", len(graphs))
print("Audio items:", len(audio_items))
print("Train indices:", len(train_idx))
print("Validation indices:", len(val_idx))
print("Test indices:", len(test_idx))

failed_paths = {
    path
    for path, error in failed_files
}

successful_audio_items = [
    (path, genre_name)
    for path, genre_name in audio_items
    if path not in failed_paths
]

print(
    "Successful audio items:",
    len(successful_audio_items)
)

print(
    "Graphs:",
    len(graphs)
)

assert (
    len(successful_audio_items)
    == len(graphs)
)

print("CNN and GNN datasets are aligned.")

import librosa
import numpy as np
import torch
import torch.nn.functional as F


MEL_SR = 22050
MEL_SECONDS = 30
N_MELS = 128


def create_logmel(audio_path):

    # Load audio
    audio, sr = librosa.load(
        audio_path,
        sr=MEL_SR,
        mono=True
    )

    # Make exactly 30 seconds
    target_length = (
        MEL_SR * MEL_SECONDS
    )

    if len(audio) < target_length:

        audio = np.pad(
            audio,
            (
                0,
                target_length - len(audio)
            )
        )

    else:

        audio = audio[:target_length]

    # Mel spectrogram
    mel = librosa.feature.melspectrogram(
        y=audio,
        sr=MEL_SR,
        n_fft=1024,
        hop_length=512,
        n_mels=N_MELS
    )

    # Convert power to logarithmic dB
    logmel = librosa.power_to_db(
        mel,
        ref=np.max
    )

    # Normalize per track
    logmel = (
        logmel - logmel.mean()
    ) / (
        logmel.std() + 1e-6
    )

    # Tensor:
    # [1, 128, time]
    tensor = torch.tensor(
        logmel,
        dtype=torch.float32
    ).unsqueeze(0)

    # Resize time dimension for
    # efficient CNN training
    tensor = tensor.unsqueeze(0)

    tensor = F.interpolate(
        tensor,
        size=(128, 256),
        mode="bilinear",
        align_corners=False
    )

    tensor = tensor.squeeze(0)

    return tensor

test_path, test_genre = (
    successful_audio_items[0]
)

test_mel = create_logmel(
    test_path
)

print("Genre:", test_genre)
print(
    "Mel tensor shape:",
    test_mel.shape
)

print(
    "Minimum:",
    test_mel.min().item()
)

print(
    "Maximum:",
    test_mel.max().item()
)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))

plt.imshow(
    test_mel.squeeze(0).numpy(),
    aspect="auto",
    origin="lower"
)

plt.title(
    f"Log-Mel Spectrogram - {test_genre}"
)

plt.xlabel("Time")
plt.ylabel("Mel Frequency Bin")

plt.colorbar()

plt.tight_layout()
plt.show()

from tqdm.auto import tqdm

mel_tensors = []
mel_labels = []

for audio_path, genre_name in tqdm(
    successful_audio_items,
    desc="Creating mel-spectrograms"
):

    mel = create_logmel(
        audio_path
    )

    mel_tensors.append(
        mel
    )

    mel_labels.append(
        genre_to_id[genre_name]
    )


mel_tensors = torch.stack(
    mel_tensors
)

mel_labels = torch.tensor(
    mel_labels,
    dtype=torch.long
)

print(
    "Mel dataset shape:",
    mel_tensors.shape
)

print(
    "Labels shape:",
    mel_labels.shape
)

train_idx_t = torch.tensor(
    train_idx,
    dtype=torch.long
)

val_idx_t = torch.tensor(
    val_idx,
    dtype=torch.long
)

test_idx_t = torch.tensor(
    test_idx,
    dtype=torch.long
)


X_train = mel_tensors[
    train_idx_t
]

y_train = mel_labels[
    train_idx_t
]

X_val = mel_tensors[
    val_idx_t
]

y_val = mel_labels[
    val_idx_t
]

X_test = mel_tensors[
    test_idx_t
]

y_test = mel_labels[
    test_idx_t
]


print(
    "CNN Train:",
    X_train.shape
)

print(
    "CNN Validation:",
    X_val.shape
)

print(
    "CNN Test:",
    X_test.shape
)

from torch.utils.data import (
    TensorDataset,
    DataLoader
)

cnn_train_dataset = TensorDataset(
    X_train,
    y_train
)

cnn_val_dataset = TensorDataset(
    X_val,
    y_val
)

cnn_test_dataset = TensorDataset(
    X_test,
    y_test
)


cnn_train_loader = DataLoader(
    cnn_train_dataset,
    batch_size=32,
    shuffle=True
)

cnn_val_loader = DataLoader(
    cnn_val_dataset,
    batch_size=32,
    shuffle=False
)

cnn_test_loader = DataLoader(
    cnn_test_dataset,
    batch_size=32,
    shuffle=False
)

print(
    "Train batches:",
    len(cnn_train_loader)
)

import torch.nn as nn
import torch.nn.functional as F


class MelCNN(nn.Module):

    def __init__(
        self,
        num_classes=10
    ):

        super().__init__()

        self.conv1 = nn.Conv2d(
            1,
            16,
            kernel_size=3,
            padding=1
        )

        self.bn1 = nn.BatchNorm2d(16)

        self.conv2 = nn.Conv2d(
            16,
            32,
            kernel_size=3,
            padding=1
        )

        self.bn2 = nn.BatchNorm2d(32)

        self.conv3 = nn.Conv2d(
            32,
            64,
            kernel_size=3,
            padding=1
        )

        self.bn3 = nn.BatchNorm2d(64)

        self.pool = nn.MaxPool2d(2)

        self.adaptive_pool = (
            nn.AdaptiveAvgPool2d(
                (4, 4)
            )
        )

        self.fc1 = nn.Linear(
            64 * 4 * 4,
            128
        )

        self.dropout = nn.Dropout(0.3)

        self.fc2 = nn.Linear(
            128,
            num_classes
        )


    def forward(self, x):

        x = self.pool(
            F.relu(
                self.bn1(
                    self.conv1(x)
                )
            )
        )

        x = self.pool(
            F.relu(
                self.bn2(
                    self.conv2(x)
                )
            )
        )

        x = self.pool(
            F.relu(
                self.bn3(
                    self.conv3(x)
                )
            )
        )

        x = self.adaptive_pool(x)

        x = torch.flatten(
            x,
            start_dim=1
        )

        x = F.relu(
            self.fc1(x)
        )

        x = self.dropout(x)

        return self.fc2(x)

cnn_model = MelCNN(
    num_classes=10
).to(device)

cnn_criterion = (
    nn.CrossEntropyLoss()
)

cnn_optimizer = torch.optim.Adam(
    cnn_model.parameters(),
    lr=0.001,
    weight_decay=1e-4
)

print(cnn_model)

print(
    "\nDevice:",
    device
)

def train_cnn_epoch():

    cnn_model.train()

    total_loss = 0

    for inputs, labels in (
        cnn_train_loader
    ):

        inputs = inputs.to(device)
        labels = labels.to(device)

        cnn_optimizer.zero_grad()

        outputs = cnn_model(
            inputs
        )

        loss = cnn_criterion(
            outputs,
            labels
        )

        loss.backward()

        cnn_optimizer.step()

        total_loss += (
            loss.item()
            * inputs.size(0)
        )

    return (
        total_loss
        / len(cnn_train_dataset)
    )

from sklearn.metrics import (
    accuracy_score,
    f1_score
)


@torch.no_grad()
def evaluate_cnn(loader):

    cnn_model.eval()

    all_true = []
    all_pred = []

    total_loss = 0

    for inputs, labels in loader:

        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = cnn_model(
            inputs
        )

        loss = cnn_criterion(
            outputs,
            labels
        )

        total_loss += (
            loss.item()
            * inputs.size(0)
        )

        predictions = (
            outputs.argmax(dim=1)
        )

        all_true.extend(
            labels.cpu().numpy()
        )

        all_pred.extend(
            predictions.cpu().numpy()
        )

    avg_loss = (
        total_loss
        / len(loader.dataset)
    )

    accuracy = accuracy_score(
        all_true,
        all_pred
    )

    macro_f1 = f1_score(
        all_true,
        all_pred,
        average="macro",
        zero_division=0
    )

    micro_f1 = f1_score(
        all_true,
        all_pred,
        average="micro",
        zero_division=0
    )

    return (
        avg_loss,
        accuracy,
        macro_f1,
        micro_f1,
        all_true,
        all_pred
    )

import copy

CNN_EPOCHS = 30

cnn_history = {
    "train_loss": [],
    "val_loss": [],
    "val_accuracy": [],
    "val_macro_f1": [],
    "val_micro_f1": []
}

best_cnn_f1 = -1
best_cnn_epoch = 0
best_cnn_state = None


for epoch in range(
    1,
    CNN_EPOCHS + 1
):

    train_loss = (
        train_cnn_epoch()
    )

    (
        val_loss,
        val_accuracy,
        val_macro_f1,
        val_micro_f1,
        _,
        _
    ) = evaluate_cnn(
        cnn_val_loader
    )

    cnn_history[
        "train_loss"
    ].append(train_loss)

    cnn_history[
        "val_loss"
    ].append(val_loss)

    cnn_history[
        "val_accuracy"
    ].append(val_accuracy)

    cnn_history[
        "val_macro_f1"
    ].append(val_macro_f1)

    cnn_history[
        "val_micro_f1"
    ].append(val_micro_f1)


    if (
        val_macro_f1
        > best_cnn_f1
    ):

        best_cnn_f1 = (
            val_macro_f1
        )

        best_cnn_epoch = epoch

        best_cnn_state = (
            copy.deepcopy(
                cnn_model.state_dict()
            )
        )


    if (
        epoch == 1
        or epoch % 5 == 0
    ):

        print(
            f"Epoch {epoch:02d} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val Acc: {val_accuracy:.4f} | "
            f"Macro-F1: {val_macro_f1:.4f} | "
            f"Micro-F1: {val_micro_f1:.4f}"
        )


print(
    "\nBest CNN epoch:",
    best_cnn_epoch
)

print(
    "Best validation Macro-F1:",
    round(
        best_cnn_f1,
        4
    )
)

cnn_model.load_state_dict(
    best_cnn_state
)

(
    cnn_test_loss,
    cnn_test_accuracy,
    cnn_test_macro_f1,
    cnn_test_micro_f1,
    cnn_test_true,
    cnn_test_pred
) = evaluate_cnn(
    cnn_test_loader
)


print(
    "FINAL CNN TEST RESULTS"
)

print(
    "----------------------"
)

print(
    "Test Loss:",
    round(
        cnn_test_loss,
        4
    )
)

print(
    "Accuracy:",
    round(
        cnn_test_accuracy,
        4
    )
)

print(
    "Macro-F1:",
    round(
        cnn_test_macro_f1,
        4
    )
)

print(
    "Micro-F1:",
    round(
        cnn_test_micro_f1,
        4
    )
)

cnn_epochs = range(
    1,
    len(cnn_history["train_loss"]) + 1
)

plt.figure(figsize=(7, 5))

plt.plot(
    cnn_epochs,
    cnn_history["train_loss"],
    label="Train Loss"
)

plt.plot(
    cnn_epochs,
    cnn_history["val_loss"],
    label="Validation Loss"
)

plt.axvline(
    best_cnn_epoch,
    linestyle="--",
    label=f"Best Epoch ({best_cnn_epoch})"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("CNN Training and Validation Loss")
plt.legend()
plt.grid(True, alpha=0.3)

plt.savefig(
    PLOT_DIR + "/cnn_loss_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

plt.figure(figsize=(7, 5))

plt.plot(
    cnn_epochs,
    cnn_history["val_macro_f1"],
    label="Validation Macro-F1"
)

plt.plot(
    cnn_epochs,
    cnn_history["val_micro_f1"],
    label="Validation Micro-F1"
)

plt.axvline(
    best_cnn_epoch,
    linestyle="--",
    label=f"Best Epoch ({best_cnn_epoch})"
)

plt.xlabel("Epoch")
plt.ylabel("F1 Score")
plt.title("CNN Validation F1 vs Epoch")
plt.legend()
plt.grid(True, alpha=0.3)

plt.savefig(
    PLOT_DIR + "/cnn_f1_curve.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import confusion_matrix

cnn_cm = confusion_matrix(
    cnn_test_true,
    cnn_test_pred
)

plt.figure(figsize=(9, 8))

plt.imshow(cnn_cm)

plt.title(
    "CNN Confusion Matrix - GTZAN"
)

plt.xlabel("Predicted Genre")
plt.ylabel("True Genre")

plt.xticks(
    range(len(genres)),
    genres,
    rotation=45,
    ha="right"
)

plt.yticks(
    range(len(genres)),
    genres
)

for i in range(cnn_cm.shape[0]):
    for j in range(cnn_cm.shape[1]):

        plt.text(
            j,
            i,
            cnn_cm[i, j],
            ha="center",
            va="center"
        )

plt.colorbar()
plt.tight_layout()

plt.savefig(
    PLOT_DIR
    + "/cnn_confusion_matrix.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

from sklearn.metrics import classification_report

cnn_report = classification_report(
    cnn_test_true,
    cnn_test_pred,
    target_names=genres,
    digits=4,
    zero_division=0
)

print(cnn_report)

cnn_results = {
    "dataset": "GTZAN",
    "model": "CNN mel-spectrogram",

    "tracks_used": 999,

    "input_shape": [
        1,
        128,
        256
    ],

    "n_mels": 128,
    "sample_rate": 22050,

    "train_size":
        len(cnn_train_dataset),

    "validation_size":
        len(cnn_val_dataset),

    "test_size":
        len(cnn_test_dataset),

    "best_epoch":
        best_cnn_epoch,

    "best_validation_macro_f1":
        float(best_cnn_f1),

    "test_loss":
        float(cnn_test_loss),

    "test_accuracy":
        float(cnn_test_accuracy),

    "test_macro_f1":
        float(cnn_test_macro_f1),

    "test_micro_f1":
        float(cnn_test_micro_f1)
}


with open(
    RESULT_DIR + "/cnn_results.json",
    "w"
) as f:

    json.dump(
        cnn_results,
        f,
        indent=4
    )

print(
    json.dumps(
        cnn_results,
        indent=4
    )
)

import pandas as pd

comparison_df = pd.DataFrame({
    "Model": [
        "GraphSAGE",
        "CNN Mel-Spectrogram"
    ],

    "Accuracy": [
        test_accuracy,
        cnn_test_accuracy
    ],

    "Macro-F1": [
        test_macro_f1,
        cnn_test_macro_f1
    ],

    "Micro-F1": [
        test_micro_f1,
        cnn_test_micro_f1
    ]
})

print(
    comparison_df.round(4)
)

comparison_plot = (
    comparison_df
    .set_index("Model")[
        [
            "Accuracy",
            "Macro-F1",
            "Micro-F1"
        ]
    ]
)

ax = comparison_plot.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.ylabel("Score")
plt.ylim(0, 1)

plt.title(
    "Task 2: GraphSAGE vs CNN on GTZAN"
)

plt.xticks(
    rotation=0
)

plt.legend(
    loc="upper left"
)

plt.tight_layout()

plt.savefig(
    PLOT_DIR
    + "/task2_graphsage_vs_cnn.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("TASK 2 FINAL SUMMARY")
print("=" * 45)

print("\nDataset:")
print("GTZAN")

print("\nTracks:")
print("999 usable tracks")

print("\nGraphSAGE")
print(
    f"Accuracy : {test_accuracy:.4f}"
)
print(
    f"Macro-F1: {test_macro_f1:.4f}"
)
print(
    f"Micro-F1: {test_micro_f1:.4f}"
)

print("\nCNN Mel-Spectrogram")
print(
    f"Accuracy : {cnn_test_accuracy:.4f}"
)
print(
    f"Macro-F1: {cnn_test_macro_f1:.4f}"
)
print(
    f"Micro-F1: {cnn_test_micro_f1:.4f}"
)

print("\nMacro-F1 difference:")
print(
    round(
        cnn_test_macro_f1
        - test_macro_f1,
        4
    )
)