# -*- coding: utf-8 -*-
"""cse425-task03project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDTvDWd3K-a0KTgbmxUvSWv3u7MJytmW

# Task 3 — GNN–BERT Fusion for Multi-Context Understanding

**Dataset:** MagnaTagATune (MTAT)  
**Benchmark split:** 18,706 train / 1,825 validation / 5,329 test  
**Prediction task:** multi-label prediction over the MTAT top-50 tags.
"""

import os
import glob
import json
import random
import subprocess
import sys

import numpy as np
import pandas as pd
import torch

SEED = 42

def set_seed(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed()

RESULT_DIR = "/kaggle/working/task3_results"
os.makedirs(RESULT_DIR, exist_ok=True)

def find_input_file(filename, path_hint=None):
    matches = glob.glob(
        f"/kaggle/input/**/{filename}",
        recursive=True
    )
    if path_hint is not None:
        hinted = [p for p in matches if path_hint.lower() in p.lower()]
        if hinted:
            matches = hinted
    if not matches:
        hint_text = f" (hint: {path_hint})" if path_hint else ""
        raise FileNotFoundError(
            f"Could not find {filename}{hint_text} under /kaggle/input"
        )
    return matches[0]

# ----- Required Task-3 files -----
TRAIN_CSV = find_input_file(
    "FINAL_task3_train.csv",
    "task3-resume-files"
)
VAL_CSV = find_input_file(
    "FINAL_task3_validation.csv",
    "task3-resume-files"
)
TEST_CSV = find_input_file(
    "FINAL_task3_test.csv",
    "task3-resume-files"
)
POS_WEIGHT_PATH = find_input_file(
    "task3_pos_weights.npy",
    "task3-resume-files"
)
BEST_BERT_PATH = find_input_file(
    "task3_bert_only_best.pt",
    "task3-resume-files"
)

TRAIN_GRAPH_PATH = find_input_file(
    "FINAL_mtt_train_graphs.pt",
    "task3-graph-files"
)
VAL_GRAPH_PATH = find_input_file(
    "FINAL_mtt_validation_graphs.pt",
    "task3-graph-files"
)
TEST_GRAPH_PATH = find_input_file(
    "FINAL_mtt_test_graphs.pt",
    "task3-graph-files"
)
GNN_CHECKPOINT_PATH = find_input_file(
    "task3_gnn_only_best.pt",
    "task3-graph-files"
)

DISTILBERT_CONFIG = find_input_file(
    "config.json",
    "distilbert-offline"
)
DISTILBERT_DIR = os.path.dirname(DISTILBERT_CONFIG)

PYG_WHEEL = find_input_file(
    "torch_geometric-2.8.0.post1-py3-none-any.whl",
    "pyg-offline"
)

# ----- Load metadata -----
FINAL_TRAIN_DF = pd.read_csv(TRAIN_CSV)
FINAL_VAL_DF = pd.read_csv(VAL_CSV)
FINAL_TEST_DF = pd.read_csv(TEST_CSV)

assert len(FINAL_TRAIN_DF) == 18706
assert len(FINAL_VAL_DF) == 1825
assert len(FINAL_TEST_DF) == 5329

top50_tags = [
    'guitar', 'classical', 'slow', 'techno', 'strings', 'drums',
    'electronic', 'rock', 'fast', 'piano', 'ambient', 'beat',
    'violin', 'vocal', 'synth', 'female', 'indian', 'opera',
    'male', 'singing', 'vocals', 'no vocals', 'harpsichord',
    'loud', 'quiet', 'flute', 'woman', 'male vocal', 'no vocal',
    'pop', 'soft', 'sitar', 'solo', 'man', 'classic', 'choir',
    'voice', 'new age', 'dance', 'female vocal', 'male voice',
    'beats', 'harp', 'cello', 'no voice', 'weird', 'country',
    'metal', 'female voice', 'choral'
]

assert len(top50_tags) == 50
for split_name, df in [
    ("train", FINAL_TRAIN_DF),
    ("validation", FINAL_VAL_DF),
    ("test", FINAL_TEST_DF),
]:
    assert all(tag in df.columns for tag in top50_tags), (
        f"Missing target column in {split_name} split"
    )

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Task-3 inputs located successfully.")
print("Split sizes:",
      len(FINAL_TRAIN_DF),
      len(FINAL_VAL_DF),
      len(FINAL_TEST_DF))
print("Target labels:", len(top50_tags))
print("Device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

"""## 1. BERT-only baseline

The BERT-only checkpoint is restored from the completed training run. We recompute validation predictions, tune a global decision threshold on **validation Macro-F1**, and then evaluate the untouched test set.
"""

import os
import json
import numpy as np
import torch
import torch.nn as nn

from torch.utils.data import (
    TensorDataset,
    DataLoader
)

from transformers import AutoModel


BERT_MAX_LENGTH = 128


def make_bert_loader(
    df,
    batch_size=32
):

    texts = (
        df["bert_text"]
        .fillna(
            "music context: no auxiliary tags"
        )
        .astype(str)
        .tolist()
    )

    encoding = bert_tokenizer(
        texts,
        padding="max_length",
        truncation=True,
        max_length=BERT_MAX_LENGTH,
        return_tensors="pt"
    )

    labels = torch.tensor(
        df[top50_tags]
        .values
        .astype(np.float32),
        dtype=torch.float32
    )

    dataset = TensorDataset(
        encoding["input_ids"],
        encoding["attention_mask"],
        labels
    )

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False
    )


bert_val_loader = make_bert_loader(
    FINAL_VAL_DF,
    batch_size=32
)

bert_test_loader = make_bert_loader(
    FINAL_TEST_DF,
    batch_size=32
)


pos_weight_tensor = torch.tensor(
    np.load(POS_WEIGHT_PATH),
    dtype=torch.float32
)


print("Validation:", len(FINAL_VAL_DF))
print("Test:", len(FINAL_TEST_DF))
print("Pos weights:", pos_weight_tensor.shape)

class Task3BERTOnly(nn.Module):

    def __init__(
        self,
        config,
        num_labels=50,
        dropout=0.2
    ):

        super().__init__()

        self.bert = AutoModel.from_config(
            config
        )

        hidden_size = (
            config.hidden_size
        )

        self.dropout = nn.Dropout(
            dropout
        )

        self.classifier = nn.Linear(
            hidden_size,
            num_labels
        )


    def encode(
        self,
        input_ids,
        attention_mask
    ):

        output = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        token_embeddings = (
            output.last_hidden_state
        )

        text_embedding = (
            token_embeddings[:, 0, :]
        )

        return (
            text_embedding,
            token_embeddings
        )


    def forward(
        self,
        input_ids,
        attention_mask
    ):

        text_embedding, _ = self.encode(
            input_ids,
            attention_mask
        )

        text_embedding = self.dropout(
            text_embedding
        )

        return self.classifier(
            text_embedding
        )


bert_model = Task3BERTOnly(
    bert_config,
    num_labels=50,
    dropout=0.2
).to(device)


bert_checkpoint = torch.load(
    BEST_BERT_PATH,
    map_location=device,
    weights_only=False
)


bert_model.load_state_dict(
    bert_checkpoint[
        "model_state_dict"
    ],
    strict=True
)


bert_criterion = nn.BCEWithLogitsLoss(
    pos_weight=(
        pos_weight_tensor.to(device)
    )
)


print(
    "Loaded epoch:",
    bert_checkpoint["epoch"]
)

print(
    "Saved Val AUC-PR:",
    round(
        bert_checkpoint["val_auc_pr"],
        4
    )
)

print(
    "Device:",
    next(
        bert_model.parameters()
    ).device
)

from sklearn.metrics import (
    f1_score,
    average_precision_score
)


@torch.no_grad()
def evaluate_bert(
    loader,
    threshold=0.5
):

    bert_model.eval()

    all_targets = []
    all_probs = []

    total_loss = 0.0
    total_examples = 0


    for (
        input_ids,
        attention_mask,
        targets
    ) in loader:

        input_ids = input_ids.to(device)

        attention_mask = (
            attention_mask.to(device)
        )

        targets = targets.to(device)


        logits = bert_model(
            input_ids,
            attention_mask
        )


        loss = bert_criterion(
            logits,
            targets
        )


        probs = torch.sigmoid(
            logits
        )


        bs = targets.shape[0]

        total_loss += (
            loss.item() * bs
        )

        total_examples += bs


        all_targets.append(
            targets.cpu().numpy()
        )

        all_probs.append(
            probs.cpu().numpy()
        )


    y_true = np.concatenate(
        all_targets,
        axis=0
    )

    y_prob = np.concatenate(
        all_probs,
        axis=0
    )


    y_pred = (
        y_prob >= threshold
    ).astype(int)


    macro_f1 = f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    micro_f1 = f1_score(
        y_true,
        y_pred,
        average="micro",
        zero_division=0
    )


    per_tag_ap = []

    for i in range(
        y_true.shape[1]
    ):

        per_tag_ap.append(
            average_precision_score(
                y_true[:, i],
                y_prob[:, i]
            )
        )


    return {

        "loss":
            total_loss
            / total_examples,

        "macro_f1":
            float(macro_f1),

        "micro_f1":
            float(micro_f1),

        "mean_auc_pr":
            float(
                np.mean(
                    per_tag_ap
                )
            ),

        "y_true":
            y_true,

        "y_prob":
            y_prob,

        "per_tag_ap":
            per_tag_ap
    }

# ==========================================
# 1. VERIFY RESTORED MODEL
# ==========================================

bert_val = evaluate_bert(
    bert_val_loader,
    threshold=0.5
)


print("\nRESTORED BERT VALIDATION @ 0.5")
print("=" * 45)

print(
    "Loss:",
    round(
        bert_val["loss"],
        4
    )
)

print(
    "Macro-F1:",
    round(
        bert_val["macro_f1"],
        4
    )
)

print(
    "Micro-F1:",
    round(
        bert_val["micro_f1"],
        4
    )
)

print(
    "Mean AUC-PR:",
    round(
        bert_val["mean_auc_pr"],
        4
    )
)


# ==========================================
# 2. VALIDATION THRESHOLD TUNING
# ==========================================

thresholds = np.arange(
    0.05,
    0.951,
    0.01
)

threshold_results = []


for threshold in thresholds:

    pred = (
        bert_val["y_prob"]
        >= threshold
    ).astype(int)

    macro = f1_score(
        bert_val["y_true"],
        pred,
        average="macro",
        zero_division=0
    )

    micro = f1_score(
        bert_val["y_true"],
        pred,
        average="micro",
        zero_division=0
    )

    threshold_results.append(
        {
            "threshold":
                float(threshold),

            "macro_f1":
                float(macro),

            "micro_f1":
                float(micro)
        }
    )


best_threshold_result = max(
    threshold_results,
    key=lambda x: x["macro_f1"]
)


BEST_BERT_THRESHOLD = (
    best_threshold_result[
        "threshold"
    ]
)


print("\nBEST VALIDATION THRESHOLD")
print("=" * 45)

print(
    "Threshold:",
    round(
        BEST_BERT_THRESHOLD,
        2
    )
)

print(
    "Validation Macro-F1:",
    round(
        best_threshold_result[
            "macro_f1"
        ],
        4
    )
)

print(
    "Validation Micro-F1:",
    round(
        best_threshold_result[
            "micro_f1"
        ],
        4
    )
)


# ==========================================
# 3. FINAL UNTOUCHED TEST
# ==========================================

bert_test = evaluate_bert(
    bert_test_loader,
    threshold=BEST_BERT_THRESHOLD
)


print("\nFINAL BERT-ONLY TEST")
print("=" * 45)

print(
    "Threshold:",
    round(
        BEST_BERT_THRESHOLD,
        2
    )
)

print(
    "Test Loss:",
    round(
        bert_test["loss"],
        4
    )
)

print(
    "Test Macro-F1:",
    round(
        bert_test["macro_f1"],
        4
    )
)

print(
    "Test Micro-F1:",
    round(
        bert_test["micro_f1"],
        4
    )
)

print(
    "Test Mean AUC-PR:",
    round(
        bert_test["mean_auc_pr"],
        4
    )
)


# ==========================================
# 4. SAVE EVERYTHING
# ==========================================

threshold_file = os.path.join(
    RESULT_DIR,
    "task3_bert_threshold_results.json"
)

with open(
    threshold_file,
    "w"
) as f:

    json.dump(
        {
            "best_threshold":
                BEST_BERT_THRESHOLD,

            "best_validation_macro_f1":
                best_threshold_result[
                    "macro_f1"
                ],

            "threshold_results":
                threshold_results
        },
        f,
        indent=4
    )


result_file = os.path.join(
    RESULT_DIR,
    "task3_bert_only_results.json"
)

with open(
    result_file,
    "w"
) as f:

    json.dump(
        {
            "best_epoch":
                int(
                    bert_checkpoint[
                        "epoch"
                    ]
                ),

            "threshold":
                float(
                    BEST_BERT_THRESHOLD
                ),

            "test_loss":
                float(
                    bert_test["loss"]
                ),

            "test_macro_f1":
                float(
                    bert_test[
                        "macro_f1"
                    ]
                ),

            "test_micro_f1":
                float(
                    bert_test[
                        "micro_f1"
                    ]
                ),

            "test_mean_auc_pr":
                float(
                    bert_test[
                        "mean_auc_pr"
                    ]
                )
        },
        f,
        indent=4
    )


np.savez_compressed(
    os.path.join(
        RESULT_DIR,
        "task3_bert_test_predictions.npz"
    ),
    y_true=bert_test["y_true"],
    y_prob=bert_test["y_prob"]
)


print("\n BERT-ONLY BASELINE COMPLETED")
print("Results saved to:", RESULT_DIR)

"""## 2. GNN-only baseline

The GraphSAGE checkpoint is restored on the same MTAT split. The graph encoder uses 12-D chroma node features and mean pooling. Its threshold is tuned only on the validation set.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.nn import SAGEConv, global_mean_pool

print("Loading graphs...")

train_graphs = torch.load(
    TRAIN_GRAPH_PATH,
    map_location="cpu",
    weights_only=False
)

val_graphs = torch.load(
    VAL_GRAPH_PATH,
    map_location="cpu",
    weights_only=False
)

test_graphs = torch.load(
    TEST_GRAPH_PATH,
    map_location="cpu",
    weights_only=False
)


print("Train:", len(train_graphs))
print("Validation:", len(val_graphs))
print("Test:", len(test_graphs))


assert len(train_graphs) == 18706
assert len(val_graphs) == 1825
assert len(test_graphs) == 5329


class Task3GraphSAGE(nn.Module):

    def __init__(
        self,
        input_dim=12,
        hidden_dim=128,
        num_labels=50,
        dropout=0.3
    ):

        super().__init__()

        self.conv1 = SAGEConv(
            input_dim,
            hidden_dim
        )

        self.conv2 = SAGEConv(
            hidden_dim,
            hidden_dim
        )

        self.dropout = nn.Dropout(
            dropout
        )

        self.classifier = nn.Linear(
            hidden_dim,
            num_labels
        )


    def encode(
        self,
        x,
        edge_index,
        batch
    ):

        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = self.dropout(x)

        x = self.conv2(
            x,
            edge_index
        )

        x = F.relu(x)

        return global_mean_pool(
            x,
            batch
        )


    def forward(
        self,
        x,
        edge_index,
        batch
    ):

        g = self.encode(
            x,
            edge_index,
            batch
        )

        return self.classifier(g)


gnn_model = Task3GraphSAGE(
    input_dim=12,
    hidden_dim=128,
    num_labels=50,
    dropout=0.3
).to(device)


gnn_checkpoint = torch.load(
    GNN_CHECKPOINT_PATH,
    map_location=device,
    weights_only=False
)


gnn_model.load_state_dict(
    gnn_checkpoint[
        "model_state_dict"
    ]
)


gnn_model.eval()

for p in gnn_model.parameters():
    p.requires_grad = False


bert_model.eval()

for p in bert_model.parameters():
    p.requires_grad = False


print("\n GNN restored successfully")

print(
    "GNN best epoch:",
    gnn_checkpoint["epoch"]
)

print(
    "GNN validation AUC-PR:",
    round(
        gnn_checkpoint["val_auc_pr"],
        4
    )
)

# ============================================================
# FINAL CURRENT GNN-ONLY EVALUATION
# No training
# ============================================================

import os
import json
import numpy as np
import torch

from torch_geometric.loader import (
    DataLoader as GeoDataLoader
)

from sklearn.metrics import (
    f1_score,
    average_precision_score
)


gnn_val_loader_final = GeoDataLoader(
    val_graphs,
    batch_size=256,
    shuffle=False
)

gnn_test_loader_final = GeoDataLoader(
    test_graphs,
    batch_size=256,
    shuffle=False
)


gnn_criterion_final = (
    torch.nn.BCEWithLogitsLoss(
        pos_weight=pos_weight_tensor.to(device)
    )
)


@torch.inference_mode()
def evaluate_current_gnn(
    loader,
    threshold=0.5
):

    gnn_model.eval()

    total_loss = 0.0
    total_n = 0

    all_true = []
    all_prob = []


    for batch in loader:

        batch = batch.to(device)

        logits = gnn_model(
            batch.x,
            batch.edge_index,
            batch.batch
        )

        targets = batch.y

        # Safety for [B, 1, 50]
        if targets.ndim == 3:
            targets = targets.squeeze(1)

        targets = targets.float()

        loss = gnn_criterion_final(
            logits,
            targets
        )

        probs = torch.sigmoid(logits)

        bs = targets.shape[0]

        total_loss += loss.item() * bs
        total_n += bs

        all_true.append(
            targets.cpu().numpy()
        )

        all_prob.append(
            probs.cpu().numpy()
        )


    y_true = np.concatenate(
        all_true,
        axis=0
    )

    y_prob = np.concatenate(
        all_prob,
        axis=0
    )

    y_pred = (
        y_prob >= threshold
    ).astype(int)


    macro = f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    micro = f1_score(
        y_true,
        y_pred,
        average="micro",
        zero_division=0
    )

    aps = [
        average_precision_score(
            y_true[:, i],
            y_prob[:, i]
        )
        for i in range(50)
    ]


    return {
        "loss": total_loss / total_n,
        "macro_f1": float(macro),
        "micro_f1": float(micro),
        "mean_auc_pr": float(np.mean(aps)),
        "y_true": y_true,
        "y_prob": y_prob
    }


# --------------------------------------------
# Validation predictions
# --------------------------------------------

gnn_val_final = evaluate_current_gnn(
    gnn_val_loader_final,
    threshold=0.5
)


# --------------------------------------------
# Tune threshold on validation Macro-F1
# --------------------------------------------

best_gnn_threshold = 0.5
best_gnn_macro = -1.0


for threshold in np.arange(
    0.05,
    0.951,
    0.01
):

    pred = (
        gnn_val_final["y_prob"]
        >= threshold
    ).astype(int)

    macro = f1_score(
        gnn_val_final["y_true"],
        pred,
        average="macro",
        zero_division=0
    )

    if macro > best_gnn_macro:

        best_gnn_macro = macro
        best_gnn_threshold = float(threshold)


# --------------------------------------------
# Untouched test
# --------------------------------------------

gnn_test_final = evaluate_current_gnn(
    gnn_test_loader_final,
    threshold=best_gnn_threshold
)


print("\nFINAL CURRENT GNN-ONLY TEST")
print("=" * 45)

print(
    "Checkpoint epoch:",
    gnn_checkpoint["epoch"]
)

print(
    "Threshold:",
    round(best_gnn_threshold, 2)
)

print(
    "Test Macro-F1:",
    round(
        gnn_test_final["macro_f1"],
        4
    )
)

print(
    "Test Micro-F1:",
    round(
        gnn_test_final["micro_f1"],
        4
    )
)

print(
    "Test Mean AUC-PR:",
    round(
        gnn_test_final["mean_auc_pr"],
        4
    )
)


with open(
    os.path.join(
        RESULT_DIR,
        "task3_gnn_only_results.json"
    ),
    "w"
) as f:

    json.dump(
        {
            "best_epoch":
                int(
                    gnn_checkpoint[
                        "epoch"
                    ]
                ),

            "best_validation_auc_pr":
                float(
                    gnn_checkpoint[
                        "val_auc_pr"
                    ]
                ),

            "threshold":
                float(
                    best_gnn_threshold
                ),

            "test_macro_f1":
                float(
                    gnn_test_final[
                        "macro_f1"
                    ]
                ),

            "test_micro_f1":
                float(
                    gnn_test_final[
                        "micro_f1"
                    ]
                ),

            "test_mean_auc_pr":
                float(
                    gnn_test_final[
                        "mean_auc_pr"
                    ]
                )
        },
        f,
        indent=4
    )


print("\nGNN BASELINE FINALIZED")

# Save the 20 example graphs required for the final project package.
GRAPH_SAMPLE_DIR = "/kaggle/working/task3_graph_samples"
os.makedirs(GRAPH_SAMPLE_DIR, exist_ok=True)

for i, graph in enumerate(train_graphs[:20]):
    torch.save(
        graph.cpu(),
        os.path.join(
            GRAPH_SAMPLE_DIR,
            f"task3_graph_sample_{i+1:02d}.pt"
        )
    )

print("Saved 20 Task-3 graph samples to:", GRAPH_SAMPLE_DIR)

"""## 3. Shared frozen embeddings for fusion ablations

For the two required fusion ablations below, the already-trained GNN and BERT encoders are first kept frozen. Their embeddings are extracted once to avoid repeating expensive encoder computation.
"""

from tqdm.auto import tqdm

from torch.utils.data import (
    TensorDataset,
    DataLoader
)

from torch_geometric.loader import (
    DataLoader as GeoDataLoader
)


# =====================================================
# GNN EMBEDDINGS
# =====================================================

@torch.inference_mode()
def get_gnn_embeddings(
    graphs,
    batch_size=256
):

    loader = GeoDataLoader(
        graphs,
        batch_size=batch_size,
        shuffle=False
    )

    all_embeddings = []

    gnn_model.eval()

    for batch in tqdm(
        loader,
        desc="Extracting GNN"
    ):

        batch = batch.to(device)

        embedding = gnn_model.encode(
            batch.x,
            batch.edge_index,
            batch.batch
        )

        all_embeddings.append(
            embedding.cpu()
        )

    return torch.cat(
        all_embeddings,
        dim=0
    )


# =====================================================
# BERT CLS EMBEDDINGS
# =====================================================

@torch.inference_mode()
def get_bert_embeddings(
    df,
    batch_size=64
):

    texts = (
        df["bert_text"]
        .fillna(
            "music context: no auxiliary tags"
        )
        .astype(str)
        .tolist()
    )

    encoding = bert_tokenizer(
        texts,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    dataset = TensorDataset(
        encoding["input_ids"],
        encoding["attention_mask"]
    )

    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False
    )

    all_embeddings = []

    bert_model.eval()

    for (
        input_ids,
        attention_mask
    ) in tqdm(
        loader,
        desc="Extracting BERT"
    ):

        input_ids = input_ids.to(device)

        attention_mask = (
            attention_mask.to(device)
        )

        text_embedding, _ = (
            bert_model.encode(
                input_ids,
                attention_mask
            )
        )

        all_embeddings.append(
            text_embedding.cpu()
        )

    return torch.cat(
        all_embeddings,
        dim=0
    )


# =====================================================
# TRAIN
# =====================================================

print("\nTRAIN")

train_g = get_gnn_embeddings(
    train_graphs
)

train_t = get_bert_embeddings(
    FINAL_TRAIN_DF
)


# =====================================================
# VALIDATION
# =====================================================

print("\nVALIDATION")

val_g = get_gnn_embeddings(
    val_graphs
)

val_t = get_bert_embeddings(
    FINAL_VAL_DF
)


# =====================================================
# TEST
# =====================================================

print("\nTEST")

test_g = get_gnn_embeddings(
    test_graphs
)

test_t = get_bert_embeddings(
    FINAL_TEST_DF
)


# =====================================================
# CHECK
# =====================================================

print("\nFINAL EMBEDDING SHAPES")
print("=" * 45)

print("Train GNN :", train_g.shape)
print("Train BERT:", train_t.shape)

print("Val GNN   :", val_g.shape)
print("Val BERT  :", val_t.shape)

print("Test GNN  :", test_g.shape)
print("Test BERT :", test_t.shape)


assert train_g.shape == (18706, 128)
assert train_t.shape == (18706, 768)

assert val_g.shape == (1825, 128)
assert val_t.shape == (1825, 768)

assert test_g.shape == (5329, 128)
assert test_t.shape == (5329, 768)


# =====================================================
# SAVE CACHE
# Important: prevents us from extracting them again
# =====================================================

CACHE_FILE = (
    "/kaggle/working/"
    "task3_frozen_embeddings.pt"
)

torch.save(
    {
        "train_g": train_g,
        "train_t": train_t,
        "val_g": val_g,
        "val_t": val_t,
        "test_g": test_g,
        "test_t": test_t
    },
    CACHE_FILE
)

print("\n EMBEDDINGS READY")
print("Saved:", CACHE_FILE)

"""## 4. Early Concatenation ablation

The 128-D graph embedding and 768-D BERT embedding are concatenated into an 896-D vector and classified with a small MLP. The best checkpoint is selected by validation mean AUC-PR.
"""

# ============================================================
# TASK 3 — EARLY CONCATENATION
# Train + Validation + Threshold Tuning + Final Test
# ============================================================

import os
import json
import numpy as np
import torch
import torch.nn as nn

from torch.utils.data import (
    TensorDataset,
    DataLoader
)

from sklearn.metrics import (
    f1_score,
    average_precision_score
)


# ------------------------------------------------------------
# 1. CREATE FUSED FEATURES
# ------------------------------------------------------------

X_train_concat = torch.cat(
    [train_g, train_t],
    dim=1
)

X_val_concat = torch.cat(
    [val_g, val_t],
    dim=1
)

X_test_concat = torch.cat(
    [test_g, test_t],
    dim=1
)


y_train_concat = torch.tensor(
    FINAL_TRAIN_DF[
        top50_tags
    ].values.astype(np.float32)
)

y_val_concat = torch.tensor(
    FINAL_VAL_DF[
        top50_tags
    ].values.astype(np.float32)
)

y_test_concat = torch.tensor(
    FINAL_TEST_DF[
        top50_tags
    ].values.astype(np.float32)
)


print("Fusion shapes:")
print("Train:", X_train_concat.shape)
print("Val  :", X_val_concat.shape)
print("Test :", X_test_concat.shape)


# ------------------------------------------------------------
# 2. DATA LOADERS
# ------------------------------------------------------------

train_concat_loader = DataLoader(
    TensorDataset(
        X_train_concat,
        y_train_concat
    ),
    batch_size=256,
    shuffle=True
)

val_concat_loader = DataLoader(
    TensorDataset(
        X_val_concat,
        y_val_concat
    ),
    batch_size=512,
    shuffle=False
)

test_concat_loader = DataLoader(
    TensorDataset(
        X_test_concat,
        y_test_concat
    ),
    batch_size=512,
    shuffle=False
)


# ------------------------------------------------------------
# 3. EARLY CONCAT MODEL
# ------------------------------------------------------------

class EarlyConcatClassifier(nn.Module):

    def __init__(self):

        super().__init__()

        self.network = nn.Sequential(

            nn.LayerNorm(896),

            nn.Linear(
                896,
                256
            ),

            nn.ReLU(),

            nn.Dropout(0.3),

            nn.Linear(
                256,
                50
            )
        )


    def forward(self, x):

        return self.network(x)


set_seed(42)

concat_model = (
    EarlyConcatClassifier()
    .to(device)
)


concat_criterion = nn.BCEWithLogitsLoss(
    pos_weight=pos_weight_tensor.to(device)
)


concat_optimizer = torch.optim.AdamW(
    concat_model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)


# ------------------------------------------------------------
# 4. EVALUATION FUNCTION
# ------------------------------------------------------------

@torch.inference_mode()
def evaluate_concat(
    loader,
    threshold=0.5
):

    concat_model.eval()

    total_loss = 0.0
    total_n = 0

    all_targets = []
    all_probs = []


    for x, y in loader:

        x = x.to(device)
        y = y.to(device)

        logits = concat_model(x)

        loss = concat_criterion(
            logits,
            y
        )

        probs = torch.sigmoid(
            logits
        )

        bs = y.size(0)

        total_loss += (
            loss.item() * bs
        )

        total_n += bs

        all_targets.append(
            y.cpu().numpy()
        )

        all_probs.append(
            probs.cpu().numpy()
        )


    y_true = np.concatenate(
        all_targets,
        axis=0
    )

    y_prob = np.concatenate(
        all_probs,
        axis=0
    )

    y_pred = (
        y_prob >= threshold
    ).astype(int)


    macro_f1 = f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    micro_f1 = f1_score(
        y_true,
        y_pred,
        average="micro",
        zero_division=0
    )


    per_tag_ap = [
        average_precision_score(
            y_true[:, i],
            y_prob[:, i]
        )
        for i in range(50)
    ]


    return {

        "loss":
            total_loss / total_n,

        "macro_f1":
            float(macro_f1),

        "micro_f1":
            float(micro_f1),

        "mean_auc_pr":
            float(
                np.mean(per_tag_ap)
            ),

        "y_true":
            y_true,

        "y_prob":
            y_prob
    }


# ------------------------------------------------------------
# 5. TRAINING
# ------------------------------------------------------------

BEST_CONCAT_PATH = os.path.join(
    RESULT_DIR,
    "task3_early_concat_best.pt"
)

best_auc = -1.0
best_epoch = 0

patience = 3
bad_epochs = 0


print("\nTRAINING EARLY CONCAT")
print("=" * 65)


for epoch in range(1, 16):

    concat_model.train()

    total_loss = 0.0
    total_n = 0


    for x, y in train_concat_loader:

        x = x.to(device)
        y = y.to(device)

        concat_optimizer.zero_grad()

        logits = concat_model(x)

        loss = concat_criterion(
            logits,
            y
        )

        loss.backward()

        concat_optimizer.step()


        bs = y.size(0)

        total_loss += (
            loss.item() * bs
        )

        total_n += bs


    train_loss = (
        total_loss / total_n
    )


    val_result = evaluate_concat(
        val_concat_loader,
        threshold=0.5
    )


    print(
        f"Epoch {epoch:02d} | "
        f"Train Loss {train_loss:.4f} | "
        f"Val Loss {val_result['loss']:.4f} | "
        f"Macro-F1@0.5 {val_result['macro_f1']:.4f} | "
        f"AUC-PR {val_result['mean_auc_pr']:.4f}"
    )


    if (
        val_result["mean_auc_pr"]
        > best_auc
    ):

        best_auc = (
            val_result[
                "mean_auc_pr"
            ]
        )

        best_epoch = epoch

        bad_epochs = 0


        torch.save(
            {
                "epoch":
                    epoch,

                "model_state_dict":
                    concat_model.state_dict(),

                "val_auc_pr":
                    best_auc
            },
            BEST_CONCAT_PATH
        )


    else:

        bad_epochs += 1


    if bad_epochs >= patience:

        print("\nEarly stopping triggered.")

        break


# ------------------------------------------------------------
# 6. LOAD BEST MODEL
# ------------------------------------------------------------

concat_checkpoint = torch.load(
    BEST_CONCAT_PATH,
    map_location=device,
    weights_only=False
)

concat_model.load_state_dict(
    concat_checkpoint[
        "model_state_dict"
    ]
)


print("\nBest epoch:", concat_checkpoint["epoch"])

print(
    "Best validation AUC-PR:",
    round(
        concat_checkpoint[
            "val_auc_pr"
        ],
        4
    )
)


# ------------------------------------------------------------
# 7. VALIDATION THRESHOLD TUNING
# ------------------------------------------------------------

best_val = evaluate_concat(
    val_concat_loader,
    threshold=0.5
)


best_threshold = 0.5
best_macro = -1.0
best_micro = 0.0


for threshold in np.arange(
    0.05,
    0.951,
    0.01
):

    predictions = (
        best_val["y_prob"]
        >= threshold
    ).astype(int)


    macro = f1_score(
        best_val["y_true"],
        predictions,
        average="macro",
        zero_division=0
    )

    micro = f1_score(
        best_val["y_true"],
        predictions,
        average="micro",
        zero_division=0
    )


    if macro > best_macro:

        best_macro = macro

        best_micro = micro

        best_threshold = float(
            threshold
        )


print("\nBEST VALIDATION THRESHOLD")
print("=" * 45)

print(
    "Threshold:",
    round(best_threshold, 2)
)

print(
    "Validation Macro-F1:",
    round(best_macro, 4)
)

print(
    "Validation Micro-F1:",
    round(best_micro, 4)
)


# ------------------------------------------------------------
# 8. FINAL TEST
# ------------------------------------------------------------

concat_test = evaluate_concat(
    test_concat_loader,
    threshold=best_threshold
)


print("\nFINAL EARLY-CONCAT TEST")
print("=" * 45)

print(
    "Threshold:",
    round(best_threshold, 2)
)

print(
    "Test Loss:",
    round(
        concat_test["loss"],
        4
    )
)

print(
    "Test Macro-F1:",
    round(
        concat_test["macro_f1"],
        4
    )
)

print(
    "Test Micro-F1:",
    round(
        concat_test["micro_f1"],
        4
    )
)

print(
    "Test Mean AUC-PR:",
    round(
        concat_test["mean_auc_pr"],
        4
    )
)


# ------------------------------------------------------------
# 9. SAVE RESULTS
# ------------------------------------------------------------

concat_results = {

    "best_epoch":
        int(
            concat_checkpoint[
                "epoch"
            ]
        ),

    "best_validation_auc_pr":
        float(
            concat_checkpoint[
                "val_auc_pr"
            ]
        ),

    "best_threshold":
        float(
            best_threshold
        ),

    "validation_macro_f1":
        float(
            best_macro
        ),

    "test_loss":
        float(
            concat_test[
                "loss"
            ]
        ),

    "test_macro_f1":
        float(
            concat_test[
                "macro_f1"
            ]
        ),

    "test_micro_f1":
        float(
            concat_test[
                "micro_f1"
            ]
        ),

    "test_mean_auc_pr":
        float(
            concat_test[
                "mean_auc_pr"
            ]
        )
}


with open(
    os.path.join(
        RESULT_DIR,
        "task3_early_concat_results.json"
    ),
    "w"
) as f:

    json.dump(
        concat_results,
        f,
        indent=4
    )


np.savez_compressed(
    os.path.join(
        RESULT_DIR,
        "task3_early_concat_predictions.npz"
    ),

    y_true=
        concat_test["y_true"],

    y_prob=
        concat_test["y_prob"]
)


print(
    "\nEARLY CONCAT COMPLETED"
)

"""## 5. Cross-Attention ablation

The graph representation is projected to the BERT hidden size and used as a **query** over the BERT token sequence (keys/values). This implements the required graph-to-text cross-attention fusion.
"""

# ============================================================
# TASK 3 — CROSS ATTENTION SETUP
# ============================================================

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

from torch.utils.data import (
    TensorDataset,
    DataLoader
)


# ------------------------------------------------------------
# CREATE DATA LOADER
# ------------------------------------------------------------

def make_cross_loader(
    graph_embeddings,
    df,
    batch_size=64,
    shuffle=False
):

    texts = (
        df["bert_text"]
        .fillna(
            "music context: no auxiliary tags"
        )
        .astype(str)
        .tolist()
    )

    enc = bert_tokenizer(
        texts,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    labels = torch.tensor(
        df[top50_tags]
        .values
        .astype(np.float32),
        dtype=torch.float32
    )

    dataset = TensorDataset(
        graph_embeddings.float(),
        enc["input_ids"],
        enc["attention_mask"],
        labels
    )

    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=0,
        pin_memory=True
    )


train_cross_loader = make_cross_loader(
    train_g,
    FINAL_TRAIN_DF,
    batch_size=64,
    shuffle=True
)

val_cross_loader = make_cross_loader(
    val_g,
    FINAL_VAL_DF,
    batch_size=64,
    shuffle=False
)

test_cross_loader = make_cross_loader(
    test_g,
    FINAL_TEST_DF,
    batch_size=64,
    shuffle=False
)


print(
    "Cross-attention loaders ready:"
)

print(
    "Train batches:",
    len(train_cross_loader)
)

print(
    "Validation batches:",
    len(val_cross_loader)
)

print(
    "Test batches:",
    len(test_cross_loader)
)


# ------------------------------------------------------------
# CROSS ATTENTION MODEL
# ------------------------------------------------------------

class CrossAttentionFusion(nn.Module):

    def __init__(
        self,
        graph_dim=128,
        bert_dim=768,
        num_heads=8,
        hidden_dim=256,
        num_labels=50,
        dropout=0.3
    ):

        super().__init__()


        # Graph embedding becomes query
        self.graph_projection = nn.Linear(
            graph_dim,
            bert_dim
        )


        # Graph query attends over
        # BERT token embeddings
        self.cross_attention = (
            nn.MultiheadAttention(
                embed_dim=bert_dim,
                num_heads=num_heads,
                dropout=0.1,
                batch_first=True
            )
        )


        self.norm = nn.LayerNorm(
            bert_dim * 2
        )


        self.fc = nn.Linear(
            bert_dim * 2,
            hidden_dim
        )


        self.dropout = nn.Dropout(
            dropout
        )


        self.classifier = nn.Linear(
            hidden_dim,
            num_labels
        )


    def forward(
        self,
        graph_embedding,
        input_ids,
        attention_mask,
        return_attention=False
    ):

        # -----------------------------
        # Frozen BERT
        # -----------------------------

        with torch.no_grad():

            _, token_embeddings = (
                bert_model.encode(
                    input_ids,
                    attention_mask
                )
            )


        token_embeddings = (
            token_embeddings.detach()
        )


        # -----------------------------
        # Graph query
        # [B, 128] -> [B, 1, 768]
        # -----------------------------

        graph_query = (
            self.graph_projection(
                graph_embedding
            )
            .unsqueeze(1)
        )


        padding_mask = (
            attention_mask == 0
        )


        # -----------------------------
        # Cross Attention
        # -----------------------------

        if return_attention:

            attended, weights = (
                self.cross_attention(
                    query=graph_query,
                    key=token_embeddings,
                    value=token_embeddings,
                    key_padding_mask=
                        padding_mask,
                    need_weights=True,
                    average_attn_weights=False
                )
            )

        else:

            attended, _ = (
                self.cross_attention(
                    query=graph_query,
                    key=token_embeddings,
                    value=token_embeddings,
                    key_padding_mask=
                        padding_mask,
                    need_weights=False
                )
            )

            weights = None


        graph_vector = (
            graph_query.squeeze(1)
        )

        attended_vector = (
            attended.squeeze(1)
        )


        # -----------------------------
        # Fusion
        # -----------------------------

        fused = torch.cat(
            [
                graph_vector,
                attended_vector
            ],
            dim=1
        )


        fused = self.norm(
            fused
        )


        z = F.relu(
            self.fc(
                fused
            )
        )


        z = self.dropout(
            z
        )


        logits = self.classifier(
            z
        )


        if return_attention:

            return (
                logits,
                z,
                weights
            )


        return logits, z


set_seed(42)

cross_model = (
    CrossAttentionFusion()
    .to(device)
)


cross_criterion = (
    nn.BCEWithLogitsLoss(
        pos_weight=
            pos_weight_tensor.to(device)
    )
)


cross_optimizer = (
    torch.optim.AdamW(
        cross_model.parameters(),
        lr=5e-4,
        weight_decay=1e-4
    )
)


print("\n CROSS-ATTENTION MODEL READY")
print(cross_model)

# ============================================================
# CROSS ATTENTION TRAIN + EVALUATE
# ============================================================

import os
import json

from sklearn.metrics import (
    f1_score,
    average_precision_score
)


# ------------------------------------------------------------
# EVALUATION
# ------------------------------------------------------------

@torch.inference_mode()
def evaluate_cross(
    loader,
    threshold=0.5,
    collect_z=False
):

    cross_model.eval()

    total_loss = 0.0
    total_n = 0

    all_targets = []
    all_probs = []
    all_z = []


    for (
        g,
        input_ids,
        attention_mask,
        targets
    ) in loader:

        g = g.to(
            device,
            non_blocking=True
        )

        input_ids = input_ids.to(
            device,
            non_blocking=True
        )

        attention_mask = (
            attention_mask.to(
                device,
                non_blocking=True
            )
        )

        targets = targets.to(
            device,
            non_blocking=True
        )


        logits, z = cross_model(
            g,
            input_ids,
            attention_mask
        )


        loss = cross_criterion(
            logits,
            targets
        )


        probs = torch.sigmoid(
            logits
        )


        bs = targets.size(0)

        total_loss += (
            loss.item() * bs
        )

        total_n += bs


        all_targets.append(
            targets.cpu().numpy()
        )

        all_probs.append(
            probs.cpu().numpy()
        )


        if collect_z:

            all_z.append(
                z.cpu().numpy()
            )


    y_true = np.concatenate(
        all_targets,
        axis=0
    )

    y_prob = np.concatenate(
        all_probs,
        axis=0
    )


    y_pred = (
        y_prob >= threshold
    ).astype(int)


    macro_f1 = f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )


    micro_f1 = f1_score(
        y_true,
        y_pred,
        average="micro",
        zero_division=0
    )


    per_tag_ap = [

        average_precision_score(
            y_true[:, i],
            y_prob[:, i]
        )

        for i in range(50)
    ]


    result = {

        "loss":
            total_loss / total_n,

        "macro_f1":
            float(macro_f1),

        "micro_f1":
            float(micro_f1),

        "mean_auc_pr":
            float(
                np.mean(
                    per_tag_ap
                )
            ),

        "y_true":
            y_true,

        "y_prob":
            y_prob
    }


    if collect_z:

        result["z"] = (
            np.concatenate(
                all_z,
                axis=0
            )
        )


    return result


# ------------------------------------------------------------
# TRAINING
# ------------------------------------------------------------

BEST_CROSS_PATH = os.path.join(
    RESULT_DIR,
    "task3_cross_attention_best.pt"
)


best_auc = -1.0
best_epoch = 0

patience = 2
bad_epochs = 0


print(
    "\nTRAINING CROSS-ATTENTION"
)

print("=" * 70)


for epoch in range(1, 7):

    cross_model.train()

    total_loss = 0.0
    total_n = 0


    for (
        g,
        input_ids,
        attention_mask,
        targets
    ) in train_cross_loader:

        g = g.to(
            device,
            non_blocking=True
        )

        input_ids = input_ids.to(
            device,
            non_blocking=True
        )

        attention_mask = (
            attention_mask.to(
                device,
                non_blocking=True
            )
        )

        targets = targets.to(
            device,
            non_blocking=True
        )


        cross_optimizer.zero_grad(
            set_to_none=True
        )


        logits, _ = cross_model(
            g,
            input_ids,
            attention_mask
        )


        loss = cross_criterion(
            logits,
            targets
        )


        loss.backward()

        cross_optimizer.step()


        bs = targets.size(0)

        total_loss += (
            loss.item() * bs
        )

        total_n += bs


    train_loss = (
        total_loss / total_n
    )


    val_result = evaluate_cross(
        val_cross_loader,
        threshold=0.5
    )


    print(
        f"Epoch {epoch:02d} | "
        f"Train Loss {train_loss:.4f} | "
        f"Val Loss {val_result['loss']:.4f} | "
        f"Macro-F1@0.5 "
        f"{val_result['macro_f1']:.4f} | "
        f"AUC-PR "
        f"{val_result['mean_auc_pr']:.4f}"
    )


    if (
        val_result["mean_auc_pr"]
        > best_auc
    ):

        best_auc = (
            val_result[
                "mean_auc_pr"
            ]
        )

        best_epoch = epoch

        bad_epochs = 0


        torch.save(
            {
                "epoch":
                    epoch,

                "model_state_dict":
                    cross_model.state_dict(),

                "val_auc_pr":
                    float(best_auc)
            },

            BEST_CROSS_PATH
        )


    else:

        bad_epochs += 1


    if bad_epochs >= patience:

        print(
            "\nEarly stopping triggered."
        )

        break


# ------------------------------------------------------------
# LOAD BEST
# ------------------------------------------------------------

cross_checkpoint = torch.load(
    BEST_CROSS_PATH,
    map_location=device,
    weights_only=False
)


cross_model.load_state_dict(
    cross_checkpoint[
        "model_state_dict"
    ]
)


print(
    "\nBest epoch:",
    cross_checkpoint["epoch"]
)

print(
    "Best validation AUC-PR:",
    round(
        cross_checkpoint[
            "val_auc_pr"
        ],
        4
    )
)


# ------------------------------------------------------------
# THRESHOLD TUNING
# ------------------------------------------------------------

cross_val = evaluate_cross(
    val_cross_loader,
    threshold=0.5
)


best_threshold = 0.5
best_macro = -1
best_micro = 0


for threshold in np.arange(
    0.05,
    0.951,
    0.01
):

    pred = (
        cross_val["y_prob"]
        >= threshold
    ).astype(int)


    macro = f1_score(
        cross_val["y_true"],
        pred,
        average="macro",
        zero_division=0
    )


    micro = f1_score(
        cross_val["y_true"],
        pred,
        average="micro",
        zero_division=0
    )


    if macro > best_macro:

        best_macro = macro

        best_micro = micro

        best_threshold = float(
            threshold
        )


print(
    "\nBEST VALIDATION THRESHOLD"
)

print("=" * 45)

print(
    "Threshold:",
    round(
        best_threshold,
        2
    )
)

print(
    "Validation Macro-F1:",
    round(
        best_macro,
        4
    )
)

print(
    "Validation Micro-F1:",
    round(
        best_micro,
        4
    )
)


# ------------------------------------------------------------
# FINAL TEST
# ------------------------------------------------------------

cross_test = evaluate_cross(
    test_cross_loader,
    threshold=best_threshold,
    collect_z=True
)


print(
    "\nFINAL CROSS-ATTENTION TEST"
)

print("=" * 45)


print(
    "Threshold:",
    round(
        best_threshold,
        2
    )
)


print(
    "Test Loss:",
    round(
        cross_test[
            "loss"
        ],
        4
    )
)


print(
    "Test Macro-F1:",
    round(
        cross_test[
            "macro_f1"
        ],
        4
    )
)


print(
    "Test Micro-F1:",
    round(
        cross_test[
            "micro_f1"
        ],
        4
    )
)


print(
    "Test Mean AUC-PR:",
    round(
        cross_test[
            "mean_auc_pr"
        ],
        4
    )
)


# ------------------------------------------------------------
# SAVE
# ------------------------------------------------------------

cross_results = {

    "best_epoch":
        int(
            cross_checkpoint[
                "epoch"
            ]
        ),

    "best_validation_auc_pr":
        float(
            cross_checkpoint[
                "val_auc_pr"
            ]
        ),

    "best_threshold":
        float(
            best_threshold
        ),

    "validation_macro_f1":
        float(
            best_macro
        ),

    "test_loss":
        float(
            cross_test[
                "loss"
            ]
        ),

    "test_macro_f1":
        float(
            cross_test[
                "macro_f1"
            ]
        ),

    "test_micro_f1":
        float(
            cross_test[
                "micro_f1"
            ]
        ),

    "test_mean_auc_pr":
        float(
            cross_test[
                "mean_auc_pr"
            ]
        )
}


with open(
    os.path.join(
        RESULT_DIR,
        "task3_cross_attention_results.json"
    ),
    "w"
) as f:

    json.dump(
        cross_results,
        f,
        indent=4
    )


np.savez_compressed(
    os.path.join(
        RESULT_DIR,
        "task3_cross_attention_predictions.npz"
    ),

    y_true=
        cross_test["y_true"],

    y_prob=
        cross_test["y_prob"],

    z=
        cross_test["z"]
)


print(
    "\n CROSS-ATTENTION COMPLETED"
)

"""## 6. Fused-space visualization

The t-SNE plots below use the **required frozen Cross-Attention ablation's fused representation `z`**. The first plot is colored by available genre tags. The second uses available **mood/context proxy tags** because MTAT does not provide a clean dedicated emotion taxonomy for these top-50 labels.
"""

# ============================================================
# TASK 3 — t-SNE OF FUSED CROSS-ATTENTION REPRESENTATION
# ============================================================

import os
import numpy as np
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.manifold import TSNE


# ------------------------------------------------------------
# Load fused z if needed
# ------------------------------------------------------------

if (
    "cross_test" in globals()
    and "z" in cross_test
):

    fused_z = cross_test["z"]

else:

    prediction_file = os.path.join(
        RESULT_DIR,
        "task3_cross_attention_predictions.npz"
    )

    data = np.load(
        prediction_file
    )

    fused_z = data["z"]


print(
    "Full fused representation:",
    fused_z.shape
)


# ------------------------------------------------------------
# Use deterministic subset for speed
# ------------------------------------------------------------

rng = np.random.default_rng(
    42
)

sample_size = min(
    2000,
    len(fused_z)
)

sample_indices = rng.choice(
    len(fused_z),
    size=sample_size,
    replace=False
)

z_sample = fused_z[
    sample_indices
]


# ------------------------------------------------------------
# PCA -> t-SNE
# ------------------------------------------------------------

pca = PCA(
    n_components=50,
    random_state=42
)

z_pca = pca.fit_transform(
    z_sample
)


print(
    "Running t-SNE on:",
    z_pca.shape
)


tsne = TSNE(
    n_components=2,
    perplexity=30,
    learning_rate="auto",
    init="pca",
    max_iter=1000,
    random_state=42
)

z_2d = tsne.fit_transform(
    z_pca
)


# ------------------------------------------------------------
# Ground-truth labels for coloring
# ------------------------------------------------------------

sample_df = (
    FINAL_TEST_DF
    .iloc[sample_indices]
    .reset_index(drop=True)
)


genre_tags = [
    "classical",
    "rock",
    "pop",
    "country",
    "metal",
    "techno",
    "electronic",
    "indian"
]


context_tags = [
    "slow",
    "fast",
    "ambient",
    "quiet",
    "loud",
    "soft",
    "dance",
    "weird"
]


def first_positive_label(
    row,
    candidates
):

    for tag in candidates:

        if (
            tag in row.index
            and row[tag] == 1
        ):

            return tag

    return "other"


genre_labels = sample_df.apply(
    lambda row:
        first_positive_label(
            row,
            genre_tags
        ),
    axis=1
)


context_labels = sample_df.apply(
    lambda row:
        first_positive_label(
            row,
            context_tags
        ),
    axis=1
)


# ------------------------------------------------------------
# Genre t-SNE
# ------------------------------------------------------------

plt.figure(
    figsize=(10, 7)
)

for label in genre_labels.unique():

    mask = (
        genre_labels.values
        == label
    )

    plt.scatter(
        z_2d[mask, 0],
        z_2d[mask, 1],
        s=12,
        alpha=0.65,
        label=label
    )


plt.title(
    "t-SNE of Cross-Attention Fused Representation — Genre Tags"
)

plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")

plt.legend(
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)

plt.tight_layout()


genre_path = os.path.join(
    RESULT_DIR,
    "task3_tsne_genre.png"
)

plt.savefig(
    genre_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# Context / mood-like t-SNE
# ------------------------------------------------------------

plt.figure(
    figsize=(10, 7)
)

for label in context_labels.unique():

    mask = (
        context_labels.values
        == label
    )

    plt.scatter(
        z_2d[mask, 0],
        z_2d[mask, 1],
        s=12,
        alpha=0.65,
        label=label
    )


plt.title(
    "t-SNE of Cross-Attention Fused Representation — Context Tags"
)

plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")

plt.legend(
    bbox_to_anchor=(1.05, 1),
    loc="upper left"
)

plt.tight_layout()


context_path = os.path.join(
    RESULT_DIR,
    "task3_tsne_context.png"
)

plt.savefig(
    context_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()


np.savez_compressed(
    os.path.join(
        RESULT_DIR,
        "task3_tsne_data.npz"
    ),

    indices=
        sample_indices,

    z_2d=
        z_2d
)


print("\nt-SNE completed")
print("Genre plot:", genre_path)
print("Context plot:", context_path)

"""## 7. Three qualitative graph–semantic-tag case studies

Task 3 uses MTAT auxiliary user tags as the text modality, not captions or lyrics. Therefore, these examples are reported as **graph–semantic-tag alignment** case studies. Each case shows the graph path, predictions, and the semantic tokens receiving the highest cross-attention weights.
"""

# ============================================================
# TASK 3 — THREE QUALITATIVE CASE STUDIES
# Graph path + semantic-token attention
# ============================================================

import os
import json
import numpy as np
import torch


# ------------------------------------------------------------
# Get test probabilities
# ------------------------------------------------------------

if (
    "cross_test" in globals()
    and "y_prob" in cross_test
):

    test_probs = (
        cross_test["y_prob"]
    )

    test_true = (
        cross_test["y_true"]
    )

else:

    prediction_file = os.path.join(
        RESULT_DIR,
        "task3_cross_attention_predictions.npz"
    )

    saved = np.load(
        prediction_file
    )

    test_probs = saved["y_prob"]
    test_true = saved["y_true"]


CROSS_THRESHOLD = float(cross_results["best_threshold"])


test_pred = (
    test_probs
    >= CROSS_THRESHOLD
).astype(int)


# ------------------------------------------------------------
# Per-example Jaccard
# Used to select strong / mixed / difficult examples
# ------------------------------------------------------------

def jaccard_score_example(
    y_true,
    y_pred
):

    intersection = np.logical_and(
        y_true == 1,
        y_pred == 1
    ).sum()

    union = np.logical_or(
        y_true == 1,
        y_pred == 1
    ).sum()

    if union == 0:
        return 0.0

    return intersection / union


scores = np.array([

    jaccard_score_example(
        test_true[i],
        test_pred[i]
    )

    for i in range(
        len(test_true)
    )
])


# ------------------------------------------------------------
# Only use examples with real auxiliary text
# ------------------------------------------------------------

valid_indices = []

for i in range(
    len(FINAL_TEST_DF)
):

    text = str(
        FINAL_TEST_DF.iloc[i][
            "bert_text"
        ]
    )

    if (
        "no auxiliary tags"
        not in text.lower()
        and test_true[i].sum() > 0
    ):

        valid_indices.append(i)


valid_indices = np.array(
    valid_indices
)

valid_scores = scores[
    valid_indices
]


def closest_to_quantile(q):

    target = np.quantile(
        valid_scores,
        q
    )

    position = np.argmin(
        np.abs(
            valid_scores - target
        )
    )

    return int(
        valid_indices[position]
    )


case_indices = [
    closest_to_quantile(0.90),
    closest_to_quantile(0.50),
    closest_to_quantile(0.10)
]

case_names = [
    "Strong case",
    "Mixed case",
    "Challenging case"
]


# ------------------------------------------------------------
# Simple shortest graph path
# ------------------------------------------------------------

def shortest_path(
    edge_index,
    start=0,
    goal=5
):

    edges = (
        edge_index
        .cpu()
        .numpy()
        .T
    )

    adjacency = {}

    for u, v in edges:

        u = int(u)
        v = int(v)

        adjacency.setdefault(
            u,
            set()
        ).add(v)

        adjacency.setdefault(
            v,
            set()
        ).add(u)


    queue = [
        (start, [start])
    ]

    visited = {
        start
    }


    while queue:

        node, path = queue.pop(0)

        if node == goal:

            return path

        for neighbor in adjacency.get(
            node,
            []
        ):

            if neighbor not in visited:

                visited.add(
                    neighbor
                )

                queue.append(
                    (
                        neighbor,
                        path + [neighbor]
                    )
                )

    return []


# ------------------------------------------------------------
# Analyze each case
# ------------------------------------------------------------

case_studies = []


cross_model.eval()
bert_model.eval()


for case_name, idx in zip(
    case_names,
    case_indices
):

    row = FINAL_TEST_DF.iloc[
        idx
    ]

    text = str(
        row["bert_text"]
    )


    # ---------------------------
    # True and predicted tags
    # ---------------------------

    true_tags = [

        top50_tags[i]

        for i in range(50)

        if test_true[
            idx,
            i
        ] == 1
    ]


    predicted_order = (
        np.argsort(
            test_probs[idx]
        )[::-1]
    )


    predicted_tags = [

        (
            top50_tags[i],
            float(
                test_probs[
                    idx,
                    i
                ]
            )
        )

        for i in predicted_order

        if (
            test_probs[
                idx,
                i
            ]
            >= CROSS_THRESHOLD
        )
    ]


    # ---------------------------
    # Tokenize single example
    # ---------------------------

    enc = bert_tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )


    input_ids = (
        enc["input_ids"]
        .to(device)
    )

    attention_mask = (
        enc["attention_mask"]
        .to(device)
    )


    graph_embedding = (
        test_g[
            idx:idx + 1
        ]
        .to(device)
        .float()
    )


    # ---------------------------
    # Cross-attention weights
    # ---------------------------

    with torch.inference_mode():

        logits, z, weights = (
            cross_model(
                graph_embedding,
                input_ids,
                attention_mask,
                return_attention=True
            )
        )


    # weights:
    # [batch, heads, query=1, tokens]

    token_attention = (
        weights[
            0,
            :,
            0,
            :
        ]
        .mean(dim=0)
        .cpu()
        .numpy()
    )


    token_ids = (
        enc["input_ids"][0]
        .cpu()
        .tolist()
    )


    mask_values = (
        enc[
            "attention_mask"
        ][0]
        .cpu()
        .numpy()
    )


    tokens = (
        bert_tokenizer
        .convert_ids_to_tokens(
            token_ids
        )
    )


    token_pairs = []


    for token, attn, mask in zip(
        tokens,
        token_attention,
        mask_values
    ):

        if mask == 0:
            continue

        if token in [
            "[CLS]",
            "[SEP]",
            "[PAD]"
        ]:
            continue

        token_pairs.append(
            (
                token,
                float(attn)
            )
        )


    top_attention = sorted(
        token_pairs,
        key=lambda x: x[1],
        reverse=True
    )[:8]


    # ---------------------------
    # Graph path
    # ---------------------------

    graph = test_graphs[
        idx
    ]

    path = shortest_path(
        graph.edge_index,
        start=0,
        goal=5
    )


    unique_edges = sorted(
        {
            tuple(
                sorted(
                    (
                        int(u),
                        int(v)
                    )
                )
            )

            for u, v in (
                graph.edge_index
                .cpu()
                .numpy()
                .T
            )

            if int(u) != int(v)
        }
    )


    case = {

        "case":
            case_name,

        "test_index":
            int(idx),

        "clip_id":
            str(
                row[
                    "clip_id"
                ]
            )
            if (
                "clip_id"
                in row.index
            )
            else str(idx),

        "auxiliary_text":
            text,

        "jaccard":
            float(
                scores[idx]
            ),

        "true_tags":
            true_tags,

        "predicted_tags":
            predicted_tags,

        "graph_path_0_to_5":
            path,

        "graph_edges":
            unique_edges,

        "top_attended_tokens":
            top_attention
    }


    case_studies.append(
        case
    )


    # ---------------------------
    # Print readable output
    # ---------------------------

    print(
        "\n"
        + "=" * 75
    )

    print(
        case_name.upper()
    )

    print(
        "=" * 75
    )

    print(
        "Test index:",
        idx
    )

    print(
        "Clip ID:",
        case["clip_id"]
    )

    print(
        "\nAuxiliary semantic text:"
    )

    print(text)

    print(
        "\nTrue tags:"
    )

    print(
        true_tags
    )

    print(
        "\nPredicted tags:"
    )

    for tag, prob in predicted_tags:

        print(
            f"  {tag:20s} "
            f"{prob:.3f}"
        )

    print(
        "\nGraph path "
        "segment 0 -> segment 5:"
    )

    print(path)

    print(
        "\nGraph edges:"
    )

    print(
        unique_edges
    )

    print(
        "\nTop semantic tokens "
        "attended by graph:"
    )

    for token, weight in top_attention:

        print(
            f"  {token:15s} "
            f"{weight:.4f}"
        )

    print(
        "\nExample Jaccard:",
        round(
            scores[idx],
            3
        )
    )


# ------------------------------------------------------------
# Save cases
# ------------------------------------------------------------

case_path = os.path.join(
    RESULT_DIR,
    "task3_three_case_studies.json"
)

with open(
    case_path,
    "w"
) as f:

    json.dump(
        case_studies,
        f,
        indent=4
    )


print(
    "\n THREE CASE STUDIES COMPLETED"
)

print(
    "Saved:",
    case_path
)

"""## 8. End-to-end partial fine-tuning

To satisfy the end-to-end Task-3 requirement, we additionally fine-tune the **GNN encoder**, **fusion layers**, and the **final DistilBERT transformer block** for two epochs. The remaining BERT blocks stay frozen.
"""

# ============================================================
# FINAL END-TO-END CROSS-ATTENTION SETUP
# GNN trainable + last DistilBERT layer trainable
# ============================================================

import copy
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.loader import (
    DataLoader as GeoDataLoader
)


# ------------------------------------------------------------
# Attach text tokens + labels to each graph
# ------------------------------------------------------------

def prepare_joint_graphs(
    graphs,
    df
):

    texts = (
        df["bert_text"]
        .fillna(
            "music context: no auxiliary tags"
        )
        .astype(str)
        .tolist()
    )

    enc = bert_tokenizer(
        texts,
        padding="max_length",
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    labels = torch.tensor(
        df[top50_tags]
        .values.astype("float32")
    )

    for i, graph in enumerate(graphs):

        graph.input_ids = (
            enc["input_ids"][
                i:i+1
            ]
        )

        graph.attention_mask = (
            enc["attention_mask"][
                i:i+1
            ]
        )

        graph.target = (
            labels[
                i:i+1
            ]
        )

    return graphs


set_seed(42)

print("Preparing paired graph-text data...")

train_joint_graphs = prepare_joint_graphs(
    train_graphs,
    FINAL_TRAIN_DF
)

val_joint_graphs = prepare_joint_graphs(
    val_graphs,
    FINAL_VAL_DF
)

test_joint_graphs = prepare_joint_graphs(
    test_graphs,
    FINAL_TEST_DF
)


train_joint_loader = GeoDataLoader(
    train_joint_graphs,
    batch_size=32,
    shuffle=True
)

val_joint_loader = GeoDataLoader(
    val_joint_graphs,
    batch_size=64,
    shuffle=False
)

test_joint_loader = GeoDataLoader(
    test_joint_graphs,
    batch_size=64,
    shuffle=False
)


# ------------------------------------------------------------
# End-to-end model
# ------------------------------------------------------------

class EndToEndCrossAttention(nn.Module):

    def __init__(
        self,
        gnn,
        bert_backbone,
        pretrained_fusion
    ):

        super().__init__()

        self.gnn = gnn

        self.bert = bert_backbone

        # Start from our already-trained
        # cross-attention fusion weights
        self.graph_projection = copy.deepcopy(
            pretrained_fusion.graph_projection
        )

        self.cross_attention = copy.deepcopy(
            pretrained_fusion.cross_attention
        )

        self.norm = copy.deepcopy(
            pretrained_fusion.norm
        )

        self.fc = copy.deepcopy(
            pretrained_fusion.fc
        )

        self.dropout = copy.deepcopy(
            pretrained_fusion.dropout
        )

        self.classifier = copy.deepcopy(
            pretrained_fusion.classifier
        )


    def forward(
        self,
        batch,
        return_z=False
    ):

        # GNN is now part of forward pass
        g = self.gnn.encode(
            batch.x,
            batch.edge_index,
            batch.batch
        )


        # Keep BERT dropout stable while still
        # allowing gradients through unfrozen layer
        self.bert.eval()

        bert_output = self.bert(
            input_ids=
                batch.input_ids,

            attention_mask=
                batch.attention_mask
        )

        H = (
            bert_output
            .last_hidden_state
        )


        q = self.graph_projection(
            g
        ).unsqueeze(1)


        attended, _ = (
            self.cross_attention(
                query=q,
                key=H,
                value=H,
                key_padding_mask=(
                    batch.attention_mask
                    == 0
                ),
                need_weights=False
            )
        )


        fused = torch.cat(
            [
                q.squeeze(1),
                attended.squeeze(1)
            ],
            dim=1
        )


        fused = self.norm(
            fused
        )

        z = F.relu(
            self.fc(
                fused
            )
        )

        z = self.dropout(
            z
        )

        logits = self.classifier(
            z
        )


        if return_z:

            return logits, z

        return logits


joint_model = EndToEndCrossAttention(
    gnn_model,
    bert_model.bert,
    cross_model
).to(device)


# ------------------------------------------------------------
# Freeze everything first
# ------------------------------------------------------------

for p in joint_model.parameters():
    p.requires_grad = False


# Train GNN encoder
for p in joint_model.gnn.conv1.parameters():
    p.requires_grad = True

for p in joint_model.gnn.conv2.parameters():
    p.requires_grad = True


# Train only LAST DistilBERT block
for p in (
    joint_model
    .bert
    .transformer
    .layer[-1]
    .parameters()
):
    p.requires_grad = True


# Train fusion layers
fusion_modules = [
    joint_model.graph_projection,
    joint_model.cross_attention,
    joint_model.norm,
    joint_model.fc,
    joint_model.classifier
]

for module in fusion_modules:

    for p in module.parameters():
        p.requires_grad = True


trainable = sum(
    p.numel()
    for p in joint_model.parameters()
    if p.requires_grad
)

total = sum(
    p.numel()
    for p in joint_model.parameters()
)


print("\n END-TO-END MODEL READY")

print(
    "Train batches:",
    len(train_joint_loader)
)

print(
    "Validation batches:",
    len(val_joint_loader)
)

print(
    "Test batches:",
    len(test_joint_loader)
)

print(
    "Trainable parameters:",
    f"{trainable:,}"
)

print(
    "Total parameters:",
    f"{total:,}"
)

print(
    "\nGNN encoder trainable: YES"
)

print(
    "Last DistilBERT block trainable: YES"
)

print(
    "Fusion trainable: YES"
)

# ============================================================
# FINAL END-TO-END CROSS-ATTENTION
# 2 Epoch Fine-tuning + Validation + Threshold + Final Test
# ============================================================

import os
import json
import numpy as np
import torch

from sklearn.metrics import (
    f1_score,
    average_precision_score
)


# ------------------------------------------------------------
# LOSS
# ------------------------------------------------------------

joint_criterion = torch.nn.BCEWithLogitsLoss(
    pos_weight=pos_weight_tensor.to(device)
)


# ------------------------------------------------------------
# DIFFERENT LEARNING RATES
# ------------------------------------------------------------

gnn_params = list(
    joint_model.gnn.conv1.parameters()
) + list(
    joint_model.gnn.conv2.parameters()
)

bert_params = list(
    joint_model
    .bert
    .transformer
    .layer[-1]
    .parameters()
)

fusion_params = (
    list(
        joint_model.graph_projection.parameters()
    )
    + list(
        joint_model.cross_attention.parameters()
    )
    + list(
        joint_model.norm.parameters()
    )
    + list(
        joint_model.fc.parameters()
    )
    + list(
        joint_model.classifier.parameters()
    )
)


joint_optimizer = torch.optim.AdamW(
    [
        {
            "params": gnn_params,
            "lr": 5e-5
        },
        {
            "params": bert_params,
            "lr": 1e-5
        },
        {
            "params": fusion_params,
            "lr": 2e-4
        }
    ],
    weight_decay=1e-4
)


# ------------------------------------------------------------
# EVALUATION
# ------------------------------------------------------------

@torch.inference_mode()
def evaluate_joint(
    loader,
    threshold=0.5,
    collect_z=False
):

    joint_model.eval()

    total_loss = 0.0
    total_n = 0

    all_true = []
    all_prob = []
    all_z = []


    for batch in loader:

        batch = batch.to(device)


        if collect_z:

            logits, z = joint_model(
                batch,
                return_z=True
            )

        else:

            logits = joint_model(
                batch,
                return_z=False
            )

            z = None


        targets = batch.target.float()

        if targets.ndim == 3:
            targets = targets.squeeze(1)


        loss = joint_criterion(
            logits,
            targets
        )


        probs = torch.sigmoid(
            logits
        )


        bs = targets.shape[0]

        total_loss += (
            loss.item() * bs
        )

        total_n += bs


        all_true.append(
            targets.cpu().numpy()
        )

        all_prob.append(
            probs.cpu().numpy()
        )


        if collect_z:

            all_z.append(
                z.cpu().numpy()
            )


    y_true = np.concatenate(
        all_true,
        axis=0
    )

    y_prob = np.concatenate(
        all_prob,
        axis=0
    )


    y_pred = (
        y_prob >= threshold
    ).astype(int)


    macro_f1 = f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )


    micro_f1 = f1_score(
        y_true,
        y_pred,
        average="micro",
        zero_division=0
    )


    per_tag_ap = [

        average_precision_score(
            y_true[:, i],
            y_prob[:, i]
        )

        for i in range(50)
    ]


    result = {

        "loss":
            total_loss / total_n,

        "macro_f1":
            float(macro_f1),

        "micro_f1":
            float(micro_f1),

        "mean_auc_pr":
            float(
                np.mean(per_tag_ap)
            ),

        "y_true":
            y_true,

        "y_prob":
            y_prob
    }


    if collect_z:

        result["z"] = np.concatenate(
            all_z,
            axis=0
        )


    return result


# ------------------------------------------------------------
# TRAIN FOR ONLY 2 EPOCHS
# ------------------------------------------------------------

BEST_JOINT_PATH = os.path.join(
    RESULT_DIR,
    "task3_end_to_end_cross_attention_best.pt"
)


best_joint_auc = -1.0
best_joint_epoch = 0


print(
    "\nFINAL END-TO-END FINE-TUNING"
)

print("=" * 72)


for epoch in range(1, 3):

    joint_model.train()

    running_loss = 0.0
    total_n = 0


    for batch in train_joint_loader:

        batch = batch.to(device)


        joint_optimizer.zero_grad(
            set_to_none=True
        )


        logits = joint_model(
            batch
        )


        targets = batch.target.float()

        if targets.ndim == 3:
            targets = targets.squeeze(1)


        loss = joint_criterion(
            logits,
            targets
        )


        loss.backward()


        torch.nn.utils.clip_grad_norm_(
            [
                p
                for p in joint_model.parameters()
                if p.requires_grad
            ],
            max_norm=1.0
        )


        joint_optimizer.step()


        bs = targets.shape[0]

        running_loss += (
            loss.item() * bs
        )

        total_n += bs


    train_loss = (
        running_loss / total_n
    )


    joint_val = evaluate_joint(
        val_joint_loader,
        threshold=0.5
    )


    print(
        f"Epoch {epoch:02d} | "
        f"Train Loss {train_loss:.4f} | "
        f"Val Loss {joint_val['loss']:.4f} | "
        f"Macro-F1@0.5 {joint_val['macro_f1']:.4f} | "
        f"Micro-F1@0.5 {joint_val['micro_f1']:.4f} | "
        f"AUC-PR {joint_val['mean_auc_pr']:.4f}"
    )


    if (
        joint_val["mean_auc_pr"]
        > best_joint_auc
    ):

        best_joint_auc = (
            joint_val[
                "mean_auc_pr"
            ]
        )

        best_joint_epoch = epoch


        torch.save(
            {
                "epoch":
                    epoch,

                "model_state_dict":
                    joint_model.state_dict(),

                "val_auc_pr":
                    float(best_joint_auc)
            },

            BEST_JOINT_PATH
        )


# ------------------------------------------------------------
# LOAD BEST EPOCH
# ------------------------------------------------------------

joint_checkpoint = torch.load(
    BEST_JOINT_PATH,
    map_location=device,
    weights_only=False
)


joint_model.load_state_dict(
    joint_checkpoint[
        "model_state_dict"
    ]
)


print(
    "\nBest end-to-end epoch:",
    joint_checkpoint["epoch"]
)

print(
    "Best validation AUC-PR:",
    round(
        joint_checkpoint[
            "val_auc_pr"
        ],
        4
    )
)


# ------------------------------------------------------------
# VALIDATION THRESHOLD TUNING
# ------------------------------------------------------------

joint_val = evaluate_joint(
    val_joint_loader,
    threshold=0.5
)


best_joint_threshold = 0.5
best_joint_macro = -1.0
best_joint_micro = 0.0


for threshold in np.arange(
    0.05,
    0.951,
    0.01
):

    pred = (
        joint_val["y_prob"]
        >= threshold
    ).astype(int)


    macro = f1_score(
        joint_val["y_true"],
        pred,
        average="macro",
        zero_division=0
    )


    micro = f1_score(
        joint_val["y_true"],
        pred,
        average="micro",
        zero_division=0
    )


    if macro > best_joint_macro:

        best_joint_macro = macro
        best_joint_micro = micro

        best_joint_threshold = float(
            threshold
        )


print(
    "\nBEST END-TO-END VALIDATION THRESHOLD"
)

print("=" * 50)

print(
    "Threshold:",
    round(
        best_joint_threshold,
        2
    )
)

print(
    "Validation Macro-F1:",
    round(
        best_joint_macro,
        4
    )
)

print(
    "Validation Micro-F1:",
    round(
        best_joint_micro,
        4
    )
)


# ------------------------------------------------------------
# FINAL TEST — ONLY ONCE
# ------------------------------------------------------------

joint_test = evaluate_joint(
    test_joint_loader,
    threshold=best_joint_threshold,
    collect_z=True
)


print(
    "\nFINAL END-TO-END CROSS-ATTENTION TEST"
)

print("=" * 50)


print(
    "Threshold:",
    round(
        best_joint_threshold,
        2
    )
)

print(
    "Test Loss:",
    round(
        joint_test["loss"],
        4
    )
)

print(
    "Test Macro-F1:",
    round(
        joint_test["macro_f1"],
        4
    )
)

print(
    "Test Micro-F1:",
    round(
        joint_test["micro_f1"],
        4
    )
)

print(
    "Test Mean AUC-PR:",
    round(
        joint_test["mean_auc_pr"],
        4
    )
)


# ------------------------------------------------------------
# SAVE FINAL RESULTS
# ------------------------------------------------------------

joint_results = {

    "best_epoch":
        int(
            joint_checkpoint["epoch"]
        ),

    "best_validation_auc_pr":
        float(
            joint_checkpoint[
                "val_auc_pr"
            ]
        ),

    "threshold":
        float(
            best_joint_threshold
        ),

    "validation_macro_f1":
        float(
            best_joint_macro
        ),

    "validation_micro_f1":
        float(
            best_joint_micro
        ),

    "test_loss":
        float(
            joint_test["loss"]
        ),

    "test_macro_f1":
        float(
            joint_test[
                "macro_f1"
            ]
        ),

    "test_micro_f1":
        float(
            joint_test[
                "micro_f1"
            ]
        ),

    "test_mean_auc_pr":
        float(
            joint_test[
                "mean_auc_pr"
            ]
        )
}


with open(
    os.path.join(
        RESULT_DIR,
        "task3_end_to_end_cross_attention_results.json"
    ),
    "w"
) as f:

    json.dump(
        joint_results,
        f,
        indent=4
    )


np.savez_compressed(
    os.path.join(
        RESULT_DIR,
        "task3_end_to_end_cross_attention_predictions.npz"
    ),

    y_true=
        joint_test["y_true"],

    y_prob=
        joint_test["y_prob"],

    z=
        joint_test["z"]
)


print(
    "\nEND-TO-END CROSS-ATTENTION COMPLETED"
)

"""## 9. Final ablation results

The first table contains the **four required Task-3 ablations**. The second table adds the end-to-end partial-fine-tuning variant as an extra experiment.
"""

import matplotlib.pyplot as plt

def load_json(name):
    with open(
        os.path.join(RESULT_DIR, name),
        "r"
    ) as f:
        return json.load(f)

gnn_r = load_json("task3_gnn_only_results.json")
bert_r = load_json("task3_bert_only_results.json")
concat_r = load_json("task3_early_concat_results.json")
cross_r = load_json("task3_cross_attention_results.json")
joint_r = load_json("task3_end_to_end_cross_attention_results.json")

# Required four-model ablation table
ablation_df = pd.DataFrame({
    "Model": [
        "GNN-only",
        "BERT-only",
        "Early Concat",
        "Cross-Attention"
    ],
    "Threshold": [
        gnn_r["threshold"],
        bert_r["threshold"],
        concat_r["best_threshold"],
        cross_r["best_threshold"]
    ],
    "Macro-F1": [
        gnn_r["test_macro_f1"],
        bert_r["test_macro_f1"],
        concat_r["test_macro_f1"],
        cross_r["test_macro_f1"]
    ],
    "Micro-F1": [
        gnn_r["test_micro_f1"],
        bert_r["test_micro_f1"],
        concat_r["test_micro_f1"],
        cross_r["test_micro_f1"]
    ],
    "Mean AUC-PR": [
        gnn_r["test_mean_auc_pr"],
        bert_r["test_mean_auc_pr"],
        concat_r["test_mean_auc_pr"],
        cross_r["test_mean_auc_pr"]
    ]
})

print("TASK 3 REQUIRED ABLATION RESULTS")
print("=" * 75)
print(ablation_df.round(4).to_string(index=False))

ablation_csv = os.path.join(
    RESULT_DIR,
    "task3_final_ablation_table.csv"
)
ablation_df.to_csv(ablation_csv, index=False)

# Plot
models = ablation_df["Model"]
x = np.arange(len(models))
width = 0.24

plt.figure(figsize=(10, 6))
plt.bar(
    x - width,
    ablation_df["Macro-F1"],
    width,
    label="Macro-F1"
)
plt.bar(
    x,
    ablation_df["Micro-F1"],
    width,
    label="Micro-F1"
)
plt.bar(
    x + width,
    ablation_df["Mean AUC-PR"],
    width,
    label="Mean AUC-PR"
)
plt.xticks(x, models, rotation=15)
plt.ylabel("Score")
plt.title("Task 3: GNN-BERT Fusion Ablation Results")
plt.ylim(0, 0.45)
plt.legend()
plt.tight_layout()

plot_path = os.path.join(
    RESULT_DIR,
    "task3_ablation_comparison.png"
)
plt.savefig(plot_path, dpi=300, bbox_inches="tight")
plt.show()

# Five-model table including end-to-end extension
final_task3_results = pd.DataFrame({
    "Model": [
        "GNN-only",
        "BERT-only",
        "Early Concat",
        "Cross-Attention (Frozen)",
        "Cross-Attention (End-to-End)"
    ],
    "Threshold": [
        gnn_r["threshold"],
        bert_r["threshold"],
        concat_r["best_threshold"],
        cross_r["best_threshold"],
        joint_r["threshold"]
    ],
    "Macro-F1": [
        gnn_r["test_macro_f1"],
        bert_r["test_macro_f1"],
        concat_r["test_macro_f1"],
        cross_r["test_macro_f1"],
        joint_r["test_macro_f1"]
    ],
    "Micro-F1": [
        gnn_r["test_micro_f1"],
        bert_r["test_micro_f1"],
        concat_r["test_micro_f1"],
        cross_r["test_micro_f1"],
        joint_r["test_micro_f1"]
    ],
    "Mean AUC-PR": [
        gnn_r["test_mean_auc_pr"],
        bert_r["test_mean_auc_pr"],
        concat_r["test_mean_auc_pr"],
        cross_r["test_mean_auc_pr"],
        joint_r["test_mean_auc_pr"]
    ]
})

print("\nFINAL TASK 3 RESULTS")
print("=" * 80)
print(final_task3_results.round(4).to_string(index=False))

final_csv = os.path.join(
    RESULT_DIR,
    "task3_FINAL_results_table.csv"
)
final_task3_results.to_csv(final_csv, index=False)

best_idx = final_task3_results["Mean AUC-PR"].idxmax()
print(
    "\nBest test Mean AUC-PR:",
    final_task3_results.loc[best_idx, "Model"]
)